WITH
-- 1. 全局映射维表 (改用 universally-compatible 语法，解决 42601 语法报错)
dim_scene_mapping AS (
  SELECT * FROM (
    VALUES
('fr001b', 'all', 'ALL', 'ALL'),
    ('fr001b', 'cleanerexitint', '13退出清理模块', '6返回'),
    ('fr001b', 'cleansuccessint', '8清理完成', '5功能使用完成'),
    ('fr001b', 'coldopen', '1冷启动', '1冷启动'),
    ('fr001b', 'contactexitint', '11退出联系人恢复页', '6返回'),
    ('fr001b', 'deletesuccessint', '7删除完成', '5功能使用完成'),
    ('fr001b', 'folderclickint', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr001b', 'guidecompletionint', '3新手插屏', '3新手插屏'),
    ('fr001b', 'hotopen', '2热启动', '2热启动'),
    ('fr001b', 'notificationexitint', '12退出通知管理', '6返回'),
    ('fr001b', 'recoveredexitint', '10退出已恢复页', '6返回'),
    ('fr001b', 'recoverysuccessint', '6恢复完成', '5功能使用完成'),
    ('fr001b', 'scancompleteint', '4扫描后点ok', '4首页进二级页'),
    ('fr001b', 'scanresultexitint', '9退出扫描结果页', '6返回'),
    ('fr002b', 'all', 'ALL', 'ALL'),
    ('fr002b', 'cleanerexitint', '13退出清理模块', '6返回'),
    ('fr002b', 'cleansuccessint', '8清理完成', '5功能使用完成'),
    ('fr002b', 'coldopen', '1冷启动', '1冷启动'),
    ('fr002b', 'contactexitint', '11退出联系人恢复页', '6返回'),
    ('fr002b', 'deletesuccessint', '7删除完成', '5功能使用完成'),
    ('fr002b', 'folderclickint', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr002b', 'guidecompletionint', '3新手插屏', '3新手插屏'),
    ('fr002b', 'hotopen', '2热启动', '2热启动'),
    ('fr002b', 'notificationexitint', '12退出通知管理', '6返回'),
    ('fr002b', 'recoveredexitint', '10退出已恢复页', '6返回'),
    ('fr002b', 'recoverysuccessint', '6恢复完成', '5功能使用完成'),
    ('fr002b', 'scancompleteint', '4扫描后点ok', '4首页进二级页'),
    ('fr002b', 'scanresultexitint', '9退出扫描结果页', '6返回'),
    ('fr004', 'all', 'ALL', 'ALL'),
    ('fr004', 'clean_complete_int', '8清理完成', '5功能使用完成'),
    ('fr004', 'cleaner_close_int', '13退出清理模块', '6返回'),
    ('fr004', 'cleaner_nav', '清理模块底部原生', '清理模块底部原生'),
    ('fr004', 'cold_splash', '1冷启动', '1冷启动'),
    ('fr004', 'contact_close_int', '11退出联系人恢复页', '6返回'),
    ('fr004', 'delete_complete_int', '7删除完成', '5功能使用完成'),
    ('fr004', 'delete_complete_nav', '删除/清理成功结果页底部原生', '删除/清理成功结果页底部原生'),
    ('fr004', 'folder_select_int', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr004', 'guide_complete_int', '3新手插屏', '3新手插屏'),
    ('fr004', 'guide_nav', '图文引导最后一步底部原生', '图文引导最后一步底部原生'),
    ('fr004', 'homepage_nav', '首页底部常驻原生', '首页底部常驻原生'),
    ('fr004', 'hot_splash', '2热启动', '2热启动'),
    ('fr004', 'info_nav', '各类型内容详情页底部原生', '各类型内容详情页底部原生'),
    ('fr004', 'language_nav', '引导流程-语言设置页底部默认原生', '引导流程-语言设置页底部默认原生'),
    ('fr004', 'ntfm_close_int', '12退出通知管理', '6返回'),
    ('fr004', 'ntfm_nav', '通知管理模块底部原生', '通知管理模块底部原生'),
    ('fr004', 'recovered_close_int', '10退出已恢复页', '6返回'),
    ('fr004', 'recovered_nav', '已恢复内容列表底部原生', '已恢复内容列表底部原生'),
    ('fr004', 'recovery_complete_int', '6恢复完成', '5功能使用完成'),
    ('fr004', 'recovery_success_nav', '各类型（含联系人）恢复成功结果页底部原生', '各类型（含联系人）恢复成功结果页底部原生'),
    ('fr004', 'remove_nav', '卸载挽回流程底部原生', '卸载挽回流程底部原生'),
    ('fr004', 'scan_complete_int', '4扫描后点ok', '4首页进二级页'),
    ('fr004', 'scan_result_close_int', '9退出扫描结果页', '6返回'),
    ('fr004', 'scan_result_list_nav', '扫描结果内容列表页底部原生', '扫描结果内容列表页底部原生'),
    ('fr004', 'scanning_nav', '扫描准备页+过程页底部原生', '扫描准备页+过程页底部原生'),
    ('fr004b', 'all', 'ALL', 'ALL'),
    ('fr004b', 'clean_complete_int', '8清理完成', '5功能使用完成'),
    ('fr004b', 'cleaner_close_int', '13退出清理模块', '6返回'),
    ('fr004b', 'cleaner_nav', '清理模块底部原生', '清理模块底部原生'),
    ('fr004b', 'cold_splash', '1冷启动', '1冷启动'),
    ('fr004b', 'contact_close_int', '11退出联系人恢复页', '6返回'),
    ('fr004b', 'delete_complete_int', '7删除完成', '5功能使用完成'),
    ('fr004b', 'delete_complete_nav', '删除/清理成功结果页底部原生', '删除/清理成功结果页底部原生'),
    ('fr004b', 'folder_select_int', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr004b', 'guide_complete_int', '3新手插屏', '3新手插屏'),
    ('fr004b', 'guide_nav', '图文引导最后一步底部原生', '图文引导最后一步底部原生'),
    ('fr004b', 'homepage_nav', '首页底部常驻原生', '首页底部常驻原生'),
    ('fr004b', 'hot_splash', '2热启动', '2热启动'),
    ('fr004b', 'info_nav', '各类型内容详情页底部原生', '各类型内容详情页底部原生'),
    ('fr004b', 'language_nav', '引导流程-语言设置页底部默认原生', '引导流程-语言设置页底部默认原生'),
    ('fr004b', 'ntfm_close_int', '12退出通知管理', '6返回'),
    ('fr004b', 'ntfm_nav', '通知管理模块底部原生', '通知管理模块底部原生'),
    ('fr004b', 'recovered_close_int', '10退出已恢复页', '6返回'),
    ('fr004b', 'recovered_nav', '已恢复内容列表底部原生', '已恢复内容列表底部原生'),
    ('fr004b', 'recovery_complete_int', '6恢复完成', '5功能使用完成'),
    ('fr004b', 'recovery_success_nav', '各类型（含联系人）恢复成功结果页底部原生', '各类型（含联系人）恢复成功结果页底部原生'),
    ('fr004b', 'remove_nav', '卸载挽回流程底部原生', '卸载挽回流程底部原生'),
    ('fr004b', 'scan_complete_int', '4扫描后点ok', '4首页进二级页'),
    ('fr004b', 'scan_result_close_int', '9退出扫描结果页', '6返回'),
    ('fr004b', 'scan_result_list_nav', '扫描结果内容列表页底部原生', '扫描结果内容列表页底部原生'),
    ('fr004b', 'scanning_nav', '扫描准备页+过程页底部原生', '扫描准备页+过程页底部原生'),
    ('fr005', 'all', 'ALL', 'ALL'),
    ('fr005', 'clean_finish_int', '8清理完成', '5功能使用完成'),
    ('fr005', 'cleaner_exit_int', '13退出清理模块', '6返回'),
    ('fr005', 'cold_open', '1冷启动', '1冷启动'),
    ('fr005', 'contact_exit_int', '11退出联系人恢复页', '6返回'),
    ('fr005', 'delete_finish_int', '7删除完成', '5功能使用完成'),
    ('fr005', 'folder_list_int', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr005', 'guide_finish_int', '3新手插屏', '3新手插屏'),
    ('fr005', 'hot_open', '2热启动', '2热启动'),
    ('fr005', 'ntfm_exit_int', '12退出通知管理', '6返回'),
    ('fr005', 'recovered_exit_int', '10退出已恢复页', '6返回'),
    ('fr005', 'recovery_finish_int', '6恢复完成', '5功能使用完成'),
    ('fr005', 'scan_finish_int', '4扫描后点ok', '4首页进二级页'),
    ('fr005', 'scan_result_exit_int', '9退出扫描结果页', '6返回'),
    ('fr005b', 'all', 'ALL', 'ALL'),
    ('fr005b', 'clean_finish_int', '8清理完成', '5功能使用完成'),
    ('fr005b', 'cleaner_exit_int', '13退出清理模块', '6返回'),
    ('fr005b', 'cold_open', '1冷启动', '1冷启动'),
    ('fr005b', 'contact_exit_int', '11退出联系人恢复页', '6返回'),
    ('fr005b', 'delete_finish_int', '7删除完成', '5功能使用完成'),
    ('fr005b', 'folder_list_int', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr005b', 'guide_finish_int', '3新手插屏', '3新手插屏'),
    ('fr005b', 'hot_open', '2热启动', '2热启动'),
    ('fr005b', 'ntfm_exit_int', '12退出通知管理', '6返回'),
    ('fr005b', 'recovered_exit_int', '10退出已恢复页', '6返回'),
    ('fr005b', 'recovery_finish_int', '6恢复完成', '5功能使用完成'),
    ('fr005b', 'scan_finish_int', '4扫描后点ok', '4首页进二级页'),
    ('fr005b', 'scan_result_exit_int', '9退出扫描结果页', '6返回'),
    ('fr006', 'all', 'ALL', 'ALL'),
    ('fr006', 'clean_int', '8清理完成', '5功能使用完成'),
    ('fr006', 'cleaner_exit_int', '13退出清理模块', '6返回'),
    ('fr006', 'cold_splash', '1冷启动', '1冷启动'),
    ('fr006', 'contact_int', '11退出联系人恢复页', '6返回'),
    ('fr006', 'delete_int', '7删除完成', '5功能使用完成'),
    ('fr006', 'folder_int', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr006', 'guide_int', '3新手插屏', '3新手插屏'),
    ('fr006', 'hot_splash', '2热启动', '2热启动'),
    ('fr006', 'ntfm_int', '12退出通知管理', '6返回'),
    ('fr006', 'recovered_int', '10退出已恢复页', '6返回'),
    ('fr006', 'recovery_int', '6恢复完成', '5功能使用完成'),
    ('fr006', 'scan_int', '4扫描后点ok', '4首页进二级页'),
    ('fr006', 'scan_result_int', '9退出扫描结果页', '6返回'),
    ('fr006b', 'all', 'ALL', 'ALL'),
    ('fr006b', 'clean_int', '8清理完成', '5功能使用完成'),
    ('fr006b', 'cleaner_exit_int', '13退出清理模块', '6返回'),
    ('fr006b', 'cold_splash', '1冷启动', '1冷启动'),
    ('fr006b', 'contact_int', '11退出联系人恢复页', '6返回'),
    ('fr006b', 'delete_int', '7删除完成', '5功能使用完成'),
    ('fr006b', 'folder_int', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr006b', 'guide_int', '3新手插屏', '3新手插屏'),
    ('fr006b', 'hot_splash', '2热启动', '2热启动'),
    ('fr006b', 'ntfm_int', '12退出通知管理', '6返回'),
    ('fr006b', 'recovered_int', '10退出已恢复页', '6返回'),
    ('fr006b', 'recovery_int', '6恢复完成', '5功能使用完成'),
    ('fr006b', 'scan_int', '4扫描后点ok', '4首页进二级页'),
    ('fr006b', 'scan_result_int', '9退出扫描结果页', '6返回'),
    ('fr07', 'all', 'ALL', 'ALL'),
    ('fr07', 'dnc8_rc', '8清理完成', '5功能使用完成'),
    ('fr07', 'dnd7_rc', '7删除完成', '5功能使用完成'),
    ('fr07', 'dnr6_rc', '6恢复完成', '5功能使用完成'),
    ('fr07', 'fol5_rc', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr07', 'gde3_rc', '3新手插屏', '3新手插屏'),
    ('fr07', 'leco11_rc', '1冷启动', '1冷启动'),
    ('fr07', 'leco12_rc', '2热启动', '2热启动'),
    ('fr07', 'lgg2_rc', '7语言页原生', '7新手原生'),
    ('fr07', 'rced10_rc', '10退出已恢复页', '6返回'),
    ('fr07', 'rcln13_rc', '13退出清理模块', '6返回'),
    ('fr07', 'rctc11_rc', '11退出联系人恢复页', '6返回'),
    ('fr07', 'rfir9_rc', '9退出扫描结果页', '6返回'),
    ('fr07', 'rntm12_rc', '12退出通知管理', '6返回'),
    ('fr07', 'sfir4_rc', '4扫描后点ok', '4首页进二级页'),
    ('fr07b', 'all', 'ALL', 'ALL'),
    ('fr07b', 'dnc8_rc', '8清理完成', '5功能使用完成'),
    ('fr07b', 'dnd7_rc', '7删除完成', '5功能使用完成'),
    ('fr07b', 'dnr6_rc', '6恢复完成', '5功能使用完成'),
    ('fr07b', 'fol5_rc', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr07b', 'gde3_rc', '3新手插屏', '3新手插屏'),
    ('fr07b', 'leco11_rc', '1冷启动', '1冷启动'),
    ('fr07b', 'leco12_rc', '2热启动', '2热启动'),
    ('fr07b', 'lgg2_rc', '7语言页原生', '7新手原生'),
    ('fr07b', 'rced10_rc', '10退出已恢复页', '6返回'),
    ('fr07b', 'rcln13_rc', '13退出清理模块', '6返回'),
    ('fr07b', 'rctc11_rc', '11退出联系人恢复页', '6返回'),
    ('fr07b', 'rfir9_rc', '9退出扫描结果页', '6返回'),
    ('fr07b', 'rntm12_rc', '12退出通知管理', '6返回'),
    ('fr07b', 'sfir4_rc', '4扫描后点ok', '4首页进二级页'),
    ('fr08', 'all', 'ALL', 'ALL'),
    ('fr08', 'coopn_rp', '1冷启动', '1冷启动'),
    ('fr08', 'docl_pf8', '8清理完成', '5功能使用完成'),
    ('fr08', 'doclcfm_pf4', '4扫描后点ok', '4首页进二级页'),
    ('fr08', 'dode_pf7', '7删除完成', '5功能使用完成'),
    ('fr08', 'dorc_pf6', '6恢复完成', '5功能使用完成'),
    ('fr08', 'excln_pf13', '13退出清理模块', '6返回'),
    ('fr08', 'excota_pf11', '11退出联系人恢复页', '6返回'),
    ('fr08', 'exdorc_pf10', '10退出已恢复页', '6返回'),
    ('fr08', 'exrstcfm_pf9', '9退出扫描结果页', '6返回'),
    ('fr08', 'extzgl_pf12', '12退出通知管理', '6返回'),
    ('fr08', 'fder_pf5', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr08', 'gude_pf3', '3新手插屏', '3新手插屏'),
    ('fr08', 'hoopn_rp', '2热启动', '2热启动'),
    ('fr08', 'lage_pf2', '7语言页原生', '7新手原生'),
    ('fr08b', 'all', 'ALL', 'ALL'),
    ('fr08b', 'coopn_rp', '1冷启动', '1冷启动'),
    ('fr08b', 'docl_pf8', '8清理完成', '5功能使用完成'),
    ('fr08b', 'doclcfm_pf4', '4扫描后点ok', '4首页进二级页'),
    ('fr08b', 'dode_pf7', '7删除完成', '5功能使用完成'),
    ('fr08b', 'dorc_pf6', '6恢复完成', '5功能使用完成'),
    ('fr08b', 'excln_pf13', '13退出清理模块', '6返回'),
    ('fr08b', 'excota_pf11', '11退出联系人恢复页', '6返回'),
    ('fr08b', 'exdorc_pf10', '10退出已恢复页', '6返回'),
    ('fr08b', 'exrstcfm_pf9', '9退出扫描结果页', '6返回'),
    ('fr08b', 'extzgl_pf12', '12退出通知管理', '6返回'),
    ('fr08b', 'fder_pf5', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr08b', 'gude_pf3', '3新手插屏', '3新手插屏'),
    ('fr08b', 'hoopn_rp', '2热启动', '2热启动'),
    ('fr08b', 'lage_pf2', '7语言页原生', '7新手原生'),
    ('fr09', 'all', 'ALL', 'ALL'),
    ('fr09', 'baqn13_ln', '13退出清理模块', '6返回'),
    ('fr09', 'ber6_ln', '6恢复完成', '5功能使用完成'),
    ('fr09', 'bra9_ln', '9退出扫描结果页', '6返回'),
    ('fr09', 'bxd7_ln', '7删除完成', '5功能使用完成'),
    ('fr09', 'gcs3_ln', '3新手插屏', '3新手插屏'),
    ('fr09', 'lge2_ln', '7语言页原生', '7新手原生'),
    ('fr09', 'nda10_ln', '10退出已恢复页', '6返回'),
    ('fr09', 'out12_ln', '12退出通知管理', '6返回'),
    ('fr09', 'sal5_ln', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr09', 'swi11_ln', '1冷启动', '1冷启动'),
    ('fr09', 'swi12_ln', '2热启动', '2热启动'),
    ('fr09', 'szx4_ln', '4扫描后点ok', '4首页进二级页'),
    ('fr09', 'vac8_ln', '8清理完成', '5功能使用完成'),
    ('fr09', 'zsq11_ln', '11退出联系人恢复页', '6返回'),
    ('fr09b', 'all', 'ALL', 'ALL'),
    ('fr09b', 'baqn13_ln', '13退出清理模块', '6返回'),
    ('fr09b', 'ber6_ln', '6恢复完成', '5功能使用完成'),
    ('fr09b', 'bra9_ln', '9退出扫描结果页', '6返回'),
    ('fr09b', 'bxd7_ln', '7删除完成', '5功能使用完成'),
    ('fr09b', 'gcs3_ln', '3新手插屏', '3新手插屏'),
    ('fr09b', 'lge2_ln', '7语言页原生', '7新手原生'),
    ('fr09b', 'nda10_ln', '10退出已恢复页', '6返回'),
    ('fr09b', 'out12_ln', '12退出通知管理', '6返回'),
    ('fr09b', 'sal5_ln', '5扫描文件夹后点击文件夹', '4首页进二级页'),
    ('fr09b', 'swi11_ln', '1冷启动', '1冷启动'),
    ('fr09b', 'swi12_ln', '2热启动', '2热启动'),
    ('fr09b', 'szx4_ln', '4扫描后点ok', '4首页进二级页'),
    ('fr09b', 'vac8_ln', '8清理完成', '5功能使用完成'),
    ('fr09b', 'zsq11_ln', '11退出联系人恢复页', '6返回'),
    ('pt001', 'all', 'ALL', 'ALL'),
    ('pt001', 'back_int', '5返回', '6返回'),
    ('pt001', 'cold_open', '1冷启动', '1冷启动'),
    ('pt001', 'history_int', '9追踪用户明细点击历史', '5功能使用完成'),
    ('pt001', 'home_banner', '11首页底部banner', '首页banner'),
    ('pt001', 'home_click', '4首页进二级页', '4首页进二级页'),
    ('pt001', 'home_click_invite_code', '26首页点击share location后全屏广告', '4首页进二级页'),
    ('pt001', 'home_click_invite_list', '25首页点击add friends后全屏广告', '4首页进二级页'),
    ('pt001', 'home_click_manager', '32首页点击追踪管理后全屏广告', '4首页进二级页'),
    ('pt001', 'home_click_phone', '28首页点击Number Trcker后全屏广告', '4首页进二级页'),
    ('pt001', 'home_click_setting', '33首页点击设置插屏', '4首页进二级页'),
    ('pt001', 'home_click_track_list', '24首页点击view real-time location后全屏广告', '4首页进二级页'),
    ('pt001', 'home_click_zone', '27首页点击set zone后全屏广告', '4首页进二级页'),
    ('pt001', 'home_native', '12首页原生广告', '首页原生'),
    ('pt001', 'home_permission_native', '17首页权限弹窗引导底部原生', '8二级页原生'),
    ('pt001', 'hot_open', '2热启动', '2热启动'),
    ('pt001', 'invite_native', '18我有邀请码页底部原生', '8二级页原生'),
    ('pt001', 'invite_track_native', '19邀请追踪器底部原生', '8二级页原生'),
    ('pt001', 'language_native', '13语言页原生广告', '7新手原生'),
    ('pt001', 'new_guide_native', '15新手引导原生广告', '7新手原生'),
    ('pt001', 'phone_success_int', '6电话号码搜索结果插屏', '5功能使用完成'),
    ('pt001', 'route_int', '10追踪用户明细点击路线', '5功能使用完成'),
    ('pt001', 'set_name_int', '3新手插屏', '3新手插屏'),
    ('pt001', 'set_name_native', '14设备名称原生广告', '7新手原生'),
    ('pt001', 'set_zone_success_int', '8创建地理围栏成功插屏', '5功能使用完成'),
    ('pt001', 'setting_native', '21设置页原生（如何使用和电话号码之间）', '8二级页原生'),
    ('pt001', 'sos_success_int', '7SOS发生成功插屏', '5功能使用完成'),
    ('pt001', 'sos_success_native', '22SOS发送成功原生', '8二级页原生'),
    ('pt001', 'tracker_user_native', '23追踪用户详情页原生', '8二级页原生'),
    ('pt001', 'tutorial_native', '16教程底部原生', '8二级页原生'),
    ('pt001', 'zone_native', '20围栏页顶部部原生', '8二级页原生'),
    ('pt001b', 'all', 'ALL', 'ALL'),
    ('pt001b', 'back_int', '5返回', '6返回'),
    ('pt001b', 'cold_open', '1冷启动', '1冷启动'),
    ('pt001b', 'history_int', '9追踪用户明细点击历史', '5功能使用完成'),
    ('pt001b', 'home_banner', '11首页底部banner', '首页banner'),
    ('pt001b', 'home_click', '4首页进二级页', '4首页进二级页'),
    ('pt001b', 'home_click_invite_code', '26首页点击share location后全屏广告', '4首页进二级页'),
    ('pt001b', 'home_click_invite_list', '25首页点击add friends后全屏广告', '4首页进二级页'),
    ('pt001b', 'home_click_manager', '32首页点击追踪管理后全屏广告', '4首页进二级页'),
    ('pt001b', 'home_click_phone', '28首页点击Number Trcker后全屏广告', '4首页进二级页'),
    ('pt001b', 'home_click_setting', '33首页点击设置插屏', '4首页进二级页'),
    ('pt001b', 'home_click_track_list', '24首页点击view real-time location后全屏广告', '4首页进二级页'),
    ('pt001b', 'home_click_zone', '27首页点击set zone后全屏广告', '4首页进二级页'),
    ('pt001b', 'home_native', '12首页原生广告', '首页原生'),
    ('pt001b', 'home_permission_native', '17首页权限弹窗引导底部原生', '8二级页原生'),
    ('pt001b', 'hot_open', '2热启动', '2热启动'),
    ('pt001b', 'invite_native', '18我有邀请码页底部原生', '8二级页原生'),
    ('pt001b', 'invite_track_native', '19邀请追踪器底部原生', '8二级页原生'),
    ('pt001b', 'language_native', '13语言页原生广告', '7新手原生'),
    ('pt001b', 'new_guide_native', '15新手引导原生广告', '7新手原生'),
    ('pt001b', 'phone_success_int', '6电话号码搜索结果插屏', '5功能使用完成'),
    ('pt001b', 'route_int', '10追踪用户明细点击路线', '5功能使用完成'),
    ('pt001b', 'set_name_int', '3新手插屏', '3新手插屏'),
    ('pt001b', 'set_name_native', '14设备名称原生广告', '7新手原生'),
    ('pt001b', 'set_zone_success_int', '8创建地理围栏成功插屏', '5功能使用完成'),
    ('pt001b', 'setting_native', '21设置页原生（如何使用和电话号码之间）', '8二级页原生'),
    ('pt001b', 'sos_success_int', '7SOS发生成功插屏', '5功能使用完成'),
    ('pt001b', 'sos_success_native', '22SOS发送成功原生', '8二级页原生'),
    ('pt001b', 'tracker_user_native', '23追踪用户详情页原生', '8二级页原生'),
    ('pt001b', 'tutorial_native', '16教程底部原生', '8二级页原生'),
    ('pt001b', 'zone_native', '20围栏页顶部部原生', '8二级页原生'),
    ('r303', 'all', 'ALL', 'ALL'),
    ('r303', 'cleniteco', '5新手电池点清理', '5功能使用完成'),
    ('r303', 'copeneco', '1冷启动', '1冷启动'),
    ('r303', 'dneiteco', '6功能使用完成', '5功能使用完成'),
    ('r303', 'hopeneco', '2热启动', '2热启动'),
    ('r303b', 'all', 'ALL', 'ALL'),
    ('r303b', 'cleniteco', '5新手电池点清理', '5功能使用完成'),
    ('r303b', 'copeneco', '1冷启动', '1冷启动'),
    ('r303b', 'dneiteco', '6功能使用完成', '5功能使用完成'),
    ('r303b', 'hopeneco', '2热启动', '2热启动'),
    ('r303c', 'all', 'ALL', 'ALL'),
    ('r303c', 'cleniteco', '5新手电池点清理', '5功能使用完成'),
    ('r303c', 'copeneco', '1冷启动', '1冷启动'),
    ('r303c', 'dneiteco', '6功能使用完成', '5功能使用完成'),
    ('r303c', 'hopeneco', '2热启动', '2热启动'),
    ('r305b', 'all', 'ALL', 'ALL'),
    ('r305b', 'cli', '6功能使用完成', '5功能使用完成'),
    ('r305b', 'cop', '1冷启动', '1冷启动'),
    ('r305b', 'dne', '4扫描完成', '4扫描完成'),
    ('r305b', 'hop', '2热启动', '2热启动'),
    ('r305b', 'onv', '7结果页原生', '结果页原生'),
    ('r305b', 'saf', '4进入报告页', '4首页进二级页'),
    ('r305c', 'all', 'ALL', 'ALL'),
    ('r305c', 'cli', '6功能使用完成', '5功能使用完成'),
    ('r305c', 'cop', '1冷启动', '1冷启动'),
    ('r305c', 'dne', '4扫描完成', '4扫描完成'),
    ('r305c', 'hop', '2热启动', '2热启动'),
    ('r305c', 'onv', '7结果页原生', '结果页原生'),
    ('r305c', 'saf', '4进入报告页', '4首页进二级页'),
    ('r306b', 'all', 'ALL', 'ALL'),
    ('r306b', 'appclback', 'App Manager功能：删除app扫描页返回', '6返回'),
    ('r306b', 'appgnback', 'App Manager功能：功能扫描页返回', '6返回'),
    ('r306b', 'appmansanner', 'App Manager：卸载app完成页后（success页面后）', '5功能使用完成'),
    ('r306b', 'batteryfinish', '“Battery info”功能：完成页后（success页）', '4首页进二级页'),
    ('r306b', 'batteryint', '“Battery info”功能：扫描动画页后插页', '5功能使用完成'),
    ('r306b', 'battgnback', 'Battery info”功能：功能扫描页返回', '6返回'),
    ('r306b', 'battwcback', 'Battery info”功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r306b', 'coldnova', '1非首次冷启动', '1冷启动'),
    ('r306b', 'dupclback', '"Duplicate clean"功能：清理扫描页返回', '6返回'),
    ('r306b', 'dupgnback', '"Duplicate clean"功能：功能扫描页返回', '6返回'),
    ('r306b', 'duplicaint', 'Large File Cleaner：功能扫描动画后', '4首页进二级页'),
    ('r306b', 'duplifinish', '"Duplicate clean"功能：完成页后', '4首页进二级页'),
    ('r306b', 'firstbattery', '3新手扫描完成', '4首页进二级页'),
    ('r306b', 'firstcleanfinish', '首次启动，清理完成动画页后，（包括不同意授权返回）', '4首页进二级页'),
    ('r306b', 'firstcleaning', '5新手电池点清理', '5功能使用完成'),
    ('r306b', 'firstcoldnova', '1首次冷启动', '1冷启动'),
    ('r306b', 'hotnova', '2热启动', '2热启动'),
    ('r306b', 'junkclback', 'Junk clean”功能：清理扫描页返回', '6返回'),
    ('r306b', 'junkfinish', '“Junk clean”功能：完成页后', '5功能使用完成'),
    ('r306b', 'junkgnback', 'Junk clean”功能：功能扫描页返回', '6返回'),
    ('r306b', 'junkint', '“Junk clean”功能：清理完成后插页or垃圾信息页点击返回后插页', '6返回'),
    ('r306b', 'junksanner', '“Junk clean”功能：功能进入对应功能扫描页扫描结束', '4首页进二级页'),
    ('r306b', 'larclback', 'Large File Cleaner功能：清理扫描页返回', '6返回'),
    ('r306b', 'largefinish', 'Large File Cleaner：清理完成页后（success页面后）', '5功能使用完成'),
    ('r306b', 'largnback', 'Large File Cleaner功能：功能扫描页返回', '6返回'),
    ('r306b', 'memognback', '“Memory info”功能：功能扫描页返回', '6返回'),
    ('r306b', 'memoryfinish', '“Memory info”功能：完成页后', '4首页进二级页'),
    ('r306b', 'memoryint', '“Memory info”功能：扫描动画页后插页', '6返回'),
    ('r306b', 'memowcback', '“Memory info”功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r306b', 'netwcback', 'Network Traffic功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r306b', 'networkfinish', 'Network Traffic功能：完成页后', '5功能使用完成'),
    ('r306b', 'networksanner', 'Network Traffic:功能扫描动画后', '4首页进二级页'),
    ('r306b', 'newgnback', 'Network Traffic功能：功能扫描页返回', '6返回'),
    ('r306b', 'notificationsan', '“notification cleaner”功能：进入功能功能扫描动画后', '5功能使用完成'),
    ('r306b', 'notifint', '“notification cleaner”功能：清理通知后的插页', '5功能使用完成'),
    ('r306b', 'notignback', '“notification cleaner”功能：清理通知扫描页返回', '6返回'),
    ('r306b', 'recache', '“Remove Cache”功能：删除垃圾动画后插页or从垃圾信息页返回', '6返回'),
    ('r306b', 'recacheint', 'Clean Cache：功能扫描动画后', '4首页进二级页'),
    ('r306b', 'remoclback', '“Remove Cache”功能：清理扫描页返回', '6返回'),
    ('r306b', 'remognback', '“Remove Cache”功能：功能扫描页返回', '6返回'),
    ('r306b', 'screclback', 'Screenshot Cleaner功能：清理扫描页返回', '6返回'),
    ('r306b', 'screenfinish', 'Screenshot Cleaner:清理完成页后（success页面后）', '4首页进二级页'),
    ('r306b', 'screensanner', 'Screenshot Cleaner:功能扫描动画后', '5功能使用完成'),
    ('r306b', 'scregnback', 'Screenshot Cleaner功能：功能扫描页返回', '6返回'),
    ('r306b', 'speakerback', '"speaker cleaner"功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r306b', 'speakerint', '"speaker cleaner"功能：点击“cant wait“后的插页or时间清理时间已到', '5功能使用完成'),
    ('r306c', 'all', 'ALL', 'ALL'),
    ('r306c', 'appclback', 'App Manager功能：删除app扫描页返回', '6返回'),
    ('r306c', 'appgnback', 'App Manager功能：功能扫描页返回', '6返回'),
    ('r306c', 'appmansanner', 'App Manager：卸载app完成页后（success页面后）', '5功能使用完成'),
    ('r306c', 'batteryfinish', '“Battery info”功能：完成页后（success页）', '4首页进二级页'),
    ('r306c', 'batteryint', '“Battery info”功能：扫描动画页后插页', '5功能使用完成'),
    ('r306c', 'battgnback', 'Battery info”功能：功能扫描页返回', '6返回'),
    ('r306c', 'battwcback', 'Battery info”功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r306c', 'coldnova', '1非首次冷启动', '1冷启动'),
    ('r306c', 'dupclback', '"Duplicate clean"功能：清理扫描页返回', '6返回'),
    ('r306c', 'dupgnback', '"Duplicate clean"功能：功能扫描页返回', '6返回'),
    ('r306c', 'duplicaint', 'Large File Cleaner：功能扫描动画后', '4首页进二级页'),
    ('r306c', 'duplifinish', '"Duplicate clean"功能：完成页后', '4首页进二级页'),
    ('r306c', 'firstbattery', '3新手扫描完成', '4首页进二级页'),
    ('r306c', 'firstcleanfinish', '首次启动，清理完成动画页后，（包括不同意授权返回）', '4首页进二级页'),
    ('r306c', 'firstcleaning', '5新手电池点清理', '5功能使用完成'),
    ('r306c', 'firstcoldnova', '1首次冷启动', '1冷启动'),
    ('r306c', 'hotnova', '2热启动', '2热启动'),
    ('r306c', 'junkclback', 'Junk clean”功能：清理扫描页返回', '6返回'),
    ('r306c', 'junkfinish', '“Junk clean”功能：完成页后', '5功能使用完成'),
    ('r306c', 'junkgnback', 'Junk clean”功能：功能扫描页返回', '6返回'),
    ('r306c', 'junkint', '“Junk clean”功能：清理完成后插页or垃圾信息页点击返回后插页', '6返回'),
    ('r306c', 'junksanner', '“Junk clean”功能：功能进入对应功能扫描页扫描结束', '4首页进二级页'),
    ('r306c', 'larclback', 'Large File Cleaner功能：清理扫描页返回', '6返回'),
    ('r306c', 'largefinish', 'Large File Cleaner：清理完成页后（success页面后）', '5功能使用完成'),
    ('r306c', 'largnback', 'Large File Cleaner功能：功能扫描页返回', '6返回'),
    ('r306c', 'memognback', '“Memory info”功能：功能扫描页返回', '6返回'),
    ('r306c', 'memoryfinish', '“Memory info”功能：完成页后', '4首页进二级页'),
    ('r306c', 'memoryint', '“Memory info”功能：扫描动画页后插页', '6返回'),
    ('r306c', 'memowcback', '“Memory info”功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r306c', 'netwcback', 'Network Traffic功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r306c', 'networkfinish', 'Network Traffic功能：完成页后', '5功能使用完成'),
    ('r306c', 'networksanner', 'Network Traffic:功能扫描动画后', '4首页进二级页'),
    ('r306c', 'newgnback', 'Network Traffic功能：功能扫描页返回', '6返回'),
    ('r306c', 'notificationsan', '“notification cleaner”功能：进入功能功能扫描动画后', '5功能使用完成'),
    ('r306c', 'notifint', '“notification cleaner”功能：清理通知后的插页', '5功能使用完成'),
    ('r306c', 'notignback', '“notification cleaner”功能：清理通知扫描页返回', '6返回'),
    ('r306c', 'recache', '“Remove Cache”功能：删除垃圾动画后插页or从垃圾信息页返回', '6返回'),
    ('r306c', 'recacheint', 'Clean Cache：功能扫描动画后', '4首页进二级页'),
    ('r306c', 'remoclback', '“Remove Cache”功能：清理扫描页返回', '6返回'),
    ('r306c', 'remognback', '“Remove Cache”功能：功能扫描页返回', '6返回'),
    ('r306c', 'screclback', 'Screenshot Cleaner功能：清理扫描页返回', '6返回'),
    ('r306c', 'screenfinish', 'Screenshot Cleaner:清理完成页后（success页面后）', '4首页进二级页'),
    ('r306c', 'screensanner', 'Screenshot Cleaner:功能扫描动画后', '5功能使用完成'),
    ('r306c', 'scregnback', 'Screenshot Cleaner功能：功能扫描页返回', '6返回'),
    ('r306c', 'speakerback', '"speaker cleaner"功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r306c', 'speakerint', '"speaker cleaner"功能：点击“cant wait“后的插页or时间清理时间已到', '5功能使用完成'),
    ('r307b', 'act', '1冷启动', '1冷启动'),
    ('r307b', 'all', 'ALL', 'ALL'),
    ('r307b', 'cmd', '5启动点start', '5功能使用完成'),
    ('r307b', 'end', '4扫描完成', '4扫描完成'),
    ('r307b', 'sw', '2热启动', '2热启动'),
    ('r311b', 'all', 'ALL', 'ALL'),
    ('r311b', 'appscann', 'App Manager：功能扫描动画后', '4首页进二级页'),
    ('r311b', 'appsucc', 'App Manager：卸载app完成页后（success页面后）', '5功能使用完成'),
    ('r311b', 'cachescann', 'Clean Cache：功能扫描动画后', '4首页进二级页'),
    ('r311b', 'cachesucc', 'Clean Cache：清理完成页后（success页面后）', '5功能使用完成'),
    ('r311b', 'deviscann', 'Device Info:功能扫描动画后', '5功能使用完成'),
    ('r311b', 'largescann', 'Large File Cleaner：功能扫描动画后', '4首页进二级页'),
    ('r311b', 'largesucc', 'Large File Cleaner：清理完成页后（success页面后）', '5功能使用完成'),
    ('r311b', 'netscann', 'Network Traffic:功能扫描动画后', '4首页进二级页'),
    ('r311b', 'newbutt', '5新手电池点清理', '5功能使用完成'),
    ('r311b', 'newfast', '3新手扫描完成', '4首页进二级页'),
    ('r311b', 'screescann', 'Screenshot Cleaner:功能扫描动画后', '5功能使用完成'),
    ('r311b', 'screesucc', 'Screenshot Cleaner:清理完成页后（success页面后）', '4首页进二级页'),
    ('r311b', 'simiscann', 'Similar Photos:功能扫描动画后', '5功能使用完成'),
    ('r311b', 'simisucc', 'Similar Photos:清理完成页后（success页面后）', '4首页进二级页'),
    ('r311b', 'swcopen', '1非首次冷启动', '1冷启动'),
    ('r311b', 'swfirstopen', '1首次冷启动', '1冷启动'),
    ('r311b', 'swhopen', '2热启动', '2热启动'),
    ('r312', 'all', 'ALL', 'ALL'),
    ('r312', 'clnfst', '5新手电池点清理', '5功能使用完成'),
    ('r312', 'doobef', '6功能使用完成', '5功能使用完成'),
    ('r312', 'lengst', '1冷启动', '1冷启动'),
    ('r312', 'reeest', '2热启动', '2热启动'),
    ('r312', 'wanbef', '4进入报告页', '4首页进二级页'),
    ('r312c', 'all', 'ALL', 'ALL'),
    ('r312c', 'clnfst', '5新手电池点清理', '5功能使用完成'),
    ('r312c', 'doobef', '6功能使用完成', '5功能使用完成'),
    ('r312c', 'lengst', '1冷启动', '1冷启动'),
    ('r312c', 'reeest', '2热启动', '2热启动'),
    ('r312c', 'wanbef', '4进入报告页', '4首页进二级页'),
    ('r313', 'all', 'ALL', 'ALL'),
    ('r313', 'appman', 'App Manager：功能扫描动画后', '4首页进二级页'),
    ('r313', 'appmanbbb', 'App Manager返回', '6返回'),
    ('r313', 'cache', 'Clean Cache：功能扫描动画后', '4首页进二级页'),
    ('r313', 'cachebbb', 'Clean Cache返回', '6返回'),
    ('r313', 'ccopen', '1非首次冷启动', '1冷启动'),
    ('r313', 'device', 'Device Info:功能扫描动画后', '5功能使用完成'),
    ('r313', 'devicebbb', 'Device Info返回广告', '6返回'),
    ('r313', 'file', 'Large File Cleaner：功能扫描动画后', '4首页进二级页'),
    ('r313', 'filebbb', 'large file Cleaner返回', '6返回'),
    ('r313', 'firccopen', '1首次冷启动', '1冷启动'),
    ('r313', 'hhhopen', '2热启动', '2热启动'),
    ('r313', 'network', 'Network Traffic:功能扫描动画后', '4首页进二级页'),
    ('r313', 'networkbbb', '"Network Traffic"返回', '6返回'),
    ('r313', 'newbutton', '5新手电池点清理', '5功能使用完成'),
    ('r313', 'newscann', '3新手扫描完成', '4首页进二级页'),
    ('r313', 'photo', 'Similar Photos:功能扫描动画后', '5功能使用完成'),
    ('r313', 'photobbb', 'photos返回', '6返回'),
    ('r313', 'screen', 'Screenshot Cleaner:功能扫描动画后', '5功能使用完成'),
    ('r313', 'screenbbb', 'Screenshot Cleaner 返回广告', '6返回'),
    ('r313', 'succapp', 'App Manager：卸载app完成页后（success页面后）', '5功能使用完成'),
    ('r313', 'succcache', 'Clean Cache：清理完成页后（success页面后）', '5功能使用完成'),
    ('r313', 'succdevice', 'Device Info:success页面后', '4首页进二级页'),
    ('r313', 'succfile', 'Large File Cleaner：清理完成页后（success页面后）', '5功能使用完成'),
    ('r313', 'succphoto', 'Similar Photos:清理完成页后（success页面后）', '4首页进二级页'),
    ('r313', 'succscreen', 'Screenshot Cleaner:清理完成页后（success页面后）', '4首页进二级页'),
    ('r313b', 'all', 'ALL', 'ALL'),
    ('r313b', 'appman', 'App Manager：功能扫描动画后', '4首页进二级页'),
    ('r313b', 'appmanbbb', 'App Manager返回', '6返回'),
    ('r313b', 'cache', 'Clean Cache：功能扫描动画后', '4首页进二级页'),
    ('r313b', 'cachebbb', 'Clean Cache返回', '6返回'),
    ('r313b', 'ccopen', '1非首次冷启动', '1冷启动'),
    ('r313b', 'device', 'Device Info:功能扫描动画后', '5功能使用完成'),
    ('r313b', 'devicebbb', 'Device Info返回广告', '6返回'),
    ('r313b', 'file', 'Large File Cleaner：功能扫描动画后', '4首页进二级页'),
    ('r313b', 'filebbb', 'large file Cleaner返回', '6返回'),
    ('r313b', 'firccopen', '1首次冷启动', '1冷启动'),
    ('r313b', 'hhhopen', '2热启动', '2热启动'),
    ('r313b', 'network', 'Network Traffic:功能扫描动画后', '4首页进二级页'),
    ('r313b', 'networkbbb', '"Network Traffic"返回', '6返回'),
    ('r313b', 'newbutton', '5新手电池点清理', '5功能使用完成'),
    ('r313b', 'newscann', '3新手扫描完成', '4首页进二级页'),
    ('r313b', 'photo', 'Similar Photos:功能扫描动画后', '5功能使用完成'),
    ('r313b', 'photobbb', 'photos返回', '6返回'),
    ('r313b', 'screen', 'Screenshot Cleaner:功能扫描动画后', '5功能使用完成'),
    ('r313b', 'screenbbb', 'Screenshot Cleaner 返回广告', '6返回'),
    ('r313b', 'succapp', 'App Manager：卸载app完成页后（success页面后）', '5功能使用完成'),
    ('r313b', 'succcache', 'Clean Cache：清理完成页后（success页面后）', '5功能使用完成'),
    ('r313b', 'succdevice', 'Device Info:success页面后', '4首页进二级页'),
    ('r313b', 'succfile', 'Large File Cleaner：清理完成页后（success页面后）', '5功能使用完成'),
    ('r313b', 'succphoto', 'Similar Photos:清理完成页后（success页面后）', '4首页进二级页'),
    ('r313b', 'succscreen', 'Screenshot Cleaner:清理完成页后（success页面后）', '4首页进二级页'),
    ('r314', 'all', 'ALL', 'ALL'),
    ('r314', 'appman', 'App Manager：功能扫描动画后', '4首页进二级页'),
    ('r314', 'appmanback', 'App Manager返回', '6返回'),
    ('r314', 'battttery', '“Battery info”功能：扫描动画页后插页', '5功能使用完成'),
    ('r314', 'batttteryback', '“Battery info”返回', '6返回'),
    ('r314', 'batttteryclean', '“Battery info”功能：完成页后（success页）', '4首页进二级页'),
    ('r314', 'cacheclean', 'Clean Cache：功能扫描动画后', '4首页进二级页'),
    ('r314', 'cachecleanback', 'Clean Cache返回', '6返回'),
    ('r314', 'coolopen', '1首次冷启动', '1冷启动'),
    ('r314', 'finappman', 'App Manager：卸载app完成页后（success页面后）', '5功能使用完成'),
    ('r314', 'fincache', 'Clean Cache：清理完成页后（success页面后）', '5功能使用完成'),
    ('r314', 'finlarge', 'Large File Cleaner：清理完成页后（success页面后）', '5功能使用完成'),
    ('r314', 'finphoto', 'Similar Photos:清理完成页后（success页面后）', '4首页进二级页'),
    ('r314', 'finrammm', '“RAM Status”：完成页后', '4首页进二级页'),
    ('r314', 'hhopen', '2热启动', '2热启动'),
    ('r314', 'largerfile', 'Large File Cleaner：功能扫描动画后', '4首页进二级页'),
    ('r314', 'largerfileback', 'large file Cleaner返回', '6返回'),
    ('r314', 'networkkk', 'Network Traffic:功能扫描动画后', '4首页进二级页'),
    ('r314', 'networkkkback', '"Network Traffic"返回', '6返回'),
    ('r314', 'newcliclean', '5新手电池点清理', '5功能使用完成'),
    ('r314', 'newscann', '3新手扫描完成', '4首页进二级页'),
    ('r314', 'notifi', '“notification cleaner”功能：功能动画页后', '4首页进二级页'),
    ('r314', 'notifiback', '“notification cleaner”返回', '6返回'),
    ('r314', 'notificlean', '“notification cleaner”功能：清理通知后的插页', '5功能使用完成'),
    ('r314', 'photos', 'Similar Photos:功能扫描动画后', '5功能使用完成'),
    ('r314', 'photosback', 'photos返回', '6返回'),
    ('r314', 'rammm', '“RAM Status”：扫描动画页后插页', '5功能使用完成'),
    ('r314', 'rammmback', '“RAM Status”返回', '6返回'),
    ('r314', 'sppeaker', '"speaker cleaner"功能：点击“cant wait“后的插页or时间清理时间已到', '5功能使用完成'),
    ('r314', 'sppeakerback', '"speaker cleaner"返回', '6返回'),
    ('r314', 'sscoolopen', '1非首次冷启动', '1冷启动'),
    ('r314b', 'all', 'ALL', 'ALL'),
    ('r314b', 'appman', 'App Manager：功能扫描动画后', '4首页进二级页'),
    ('r314b', 'appmanback', 'App Manager返回', '6返回'),
    ('r314b', 'battttery', '“Battery info”功能：扫描动画页后插页', '5功能使用完成'),
    ('r314b', 'batttteryback', '“Battery info”返回', '6返回'),
    ('r314b', 'batttteryclean', '“Battery info”功能：完成页后（success页）', '4首页进二级页'),
    ('r314b', 'cacheclean', 'Clean Cache：功能扫描动画后', '4首页进二级页'),
    ('r314b', 'cachecleanback', 'Clean Cache返回', '6返回'),
    ('r314b', 'coolopen', '1首次冷启动', '1冷启动'),
    ('r314b', 'finappman', 'App Manager：卸载app完成页后（success页面后）', '5功能使用完成'),
    ('r314b', 'fincache', 'Clean Cache：清理完成页后（success页面后）', '5功能使用完成'),
    ('r314b', 'finlarge', 'Large File Cleaner：清理完成页后（success页面后）', '5功能使用完成'),
    ('r314b', 'finphoto', 'Similar Photos:清理完成页后（success页面后）', '4首页进二级页'),
    ('r314b', 'finrammm', '“RAM Status”：完成页后', '4首页进二级页'),
    ('r314b', 'hhopen', '2热启动', '2热启动'),
    ('r314b', 'largerfile', 'Large File Cleaner：功能扫描动画后', '4首页进二级页'),
    ('r314b', 'largerfileback', 'large file Cleaner返回', '6返回'),
    ('r314b', 'networkkk', 'Network Traffic:功能扫描动画后', '4首页进二级页'),
    ('r314b', 'networkkkback', '"Network Traffic"返回', '6返回'),
    ('r314b', 'newcliclean', '5新手电池点清理', '5功能使用完成'),
    ('r314b', 'newscann', '3新手扫描完成', '4首页进二级页'),
    ('r314b', 'notifi', '“notification cleaner”功能：功能动画页后', '4首页进二级页'),
    ('r314b', 'notifiback', '“notification cleaner”返回', '6返回'),
    ('r314b', 'notificlean', '“notification cleaner”功能：清理通知后的插页', '5功能使用完成'),
    ('r314b', 'photos', 'Similar Photos:功能扫描动画后', '5功能使用完成'),
    ('r314b', 'photosback', 'photos返回', '6返回'),
    ('r314b', 'rammm', '“RAM Status”：扫描动画页后插页', '5功能使用完成'),
    ('r314b', 'rammmback', '“RAM Status”返回', '6返回'),
    ('r314b', 'sppeaker', '"speaker cleaner"功能：点击“cant wait“后的插页or时间清理时间已到', '5功能使用完成'),
    ('r314b', 'sppeakerback', '"speaker cleaner"返回', '6返回'),
    ('r314b', 'sscoolopen', '1非首次冷启动', '1冷启动'),
    ('r316', 'all', 'ALL', 'ALL'),
    ('r316', 'djbtnop', '5新手电池点清理', '5功能使用完成'),
    ('r316', 'frontbgy', '4进入报告页', '4首页进二级页'),
    ('r316', 'frontjgy', '6功能使用完成', '5功能使用完成'),
    ('r316', 'lenop', '1冷启动', '1冷启动'),
    ('r316', 'reop', '2热启动', '2热启动'),
    ('r316b', 'all', 'ALL', 'ALL'),
    ('r316b', 'djbtnop', '5新手电池点清理', '5功能使用完成'),
    ('r316b', 'frontbgy', '4进入报告页', '4首页进二级页'),
    ('r316b', 'frontjgy', '6功能使用完成', '5功能使用完成'),
    ('r316b', 'lenop', '1冷启动', '1冷启动'),
    ('r316b', 'reop', '2热启动', '2热启动'),
    ('r319', 'all', 'ALL', 'ALL'),
    ('r319', 'scbfclan', '5新手电池点清理', '5功能使用完成'),
    ('r319', 'scfrrslt', '6功能使用完成', '5功能使用完成'),
    ('r319', 'sclcld', '1冷启动', '1冷启动'),
    ('r319', 'scqmgnbg', '4进入报告页', '4首页进二级页'),
    ('r319', 'screqd', '2热启动', '2热启动'),
    ('r319b', 'all', 'ALL', 'ALL'),
    ('r319b', 'scbfclan', '5新手电池点清理', '5功能使用完成'),
    ('r319b', 'scfrrslt', '6功能使用完成', '5功能使用完成'),
    ('r319b', 'sclcld', '1冷启动', '1冷启动'),
    ('r319b', 'scqmgnbg', '4进入报告页', '4首页进二级页'),
    ('r319b', 'screqd', '2热启动', '2热启动'),
    ('r320', 'all', 'ALL', 'ALL'),
    ('r320', 'appman_delete_back', 'App Manager功能：删除app扫描页返回', '6返回'),
    ('r320', 'appman_func_back', 'App Manager功能：功能扫描页返回', '6返回'),
    ('r320', 'appman_scan_end', 'App Manager：卸载app完成页后（success页面后）', '5功能使用完成'),
    ('r320', 'battery_finish', '“Battery info”功能：完成页后（success页）', '4首页进二级页'),
    ('r320', 'battery_func_back', 'Battery info”功能：功能扫描页返回', '6返回'),
    ('r320', 'battery_scan_back', 'Battery info”功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r320', 'battery_scan_int', '“Battery info”功能：扫描动画页后插页', '5功能使用完成'),
    ('r320', 'cache_clean_back', '“Remove Cache”功能：清理扫描页返回', '6返回'),
    ('r320', 'cache_clean_int', '“Remove Cache”功能：删除垃圾动画后插页or从垃圾信息页返回', '6返回'),
    ('r320', 'cache_func_back', '“Remove Cache”功能：功能扫描页返回', '6返回'),
    ('r320', 'cache_scan_anim', 'Clean Cache：功能扫描动画后', '4首页进二级页'),
    ('r320', 'cold_open', '1非首次冷启动', '1冷启动'),
    ('r320', 'dup_clean_back', '"Duplicate clean"功能：清理扫描页返回', '6返回'),
    ('r320', 'dup_finish', '"Duplicate clean"功能：完成页后', '4首页进二级页'),
    ('r320', 'dup_func_back', '"Duplicate clean"功能：功能扫描页返回', '6返回'),
    ('r320', 'dup_scan_int', 'Large File Cleaner：功能扫描动画后', '4首页进二级页'),
    ('r320', 'first_clean_finish', '首次启动，清理完成动画页后，（包括不同意授权返回）', '4首页进二级页'),
    ('r320', 'first_cold_open', '1首次冷启动', '1冷启动'),
    ('r320', 'first_express_clean', '5新手电池点清理', '5功能使用完成'),
    ('r320', 'first_scan_anim', '3新手扫描完成', '4首页进二级页'),
    ('r320', 'hot_open', '2热启动', '2热启动'),
    ('r320', 'junk_clean_back', 'Junk clean”功能：清理扫描页返回', '6返回'),
    ('r320', 'junk_clean_int', '“Junk clean”功能：清理完成后插页or垃圾信息页点击返回后插页', '6返回'),
    ('r320', 'junk_finish', '“Junk clean”功能：完成页后', '5功能使用完成'),
    ('r320', 'junk_func_back', 'Junk clean”功能：功能扫描页返回', '6返回'),
    ('r320', 'junk_scan_end', '“Junk clean”功能：功能进入对应功能扫描页扫描结束', '4首页进二级页'),
    ('r320', 'large_clean_back', 'Large File Cleaner功能：清理扫描页返回', '6返回'),
    ('r320', 'large_finish', 'Large File Cleaner：清理完成页后（success页面后）', '5功能使用完成'),
    ('r320', 'large_func_back', 'Large File Cleaner功能：功能扫描页返回', '6返回'),
    ('r320', 'memory_finish', '“Memory info”功能：完成页后', '4首页进二级页'),
    ('r320', 'memory_func_back', '“Memory info”功能：功能扫描页返回', '6返回'),
    ('r320', 'memory_scan_back', '“Memory info”功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r320', 'memory_scan_int', '“Memory info”功能：扫描动画页后插页', '6返回'),
    ('r320', 'network_finish', 'Network Traffic功能：完成页后', '5功能使用完成'),
    ('r320', 'network_func_back', 'Network Traffic功能：功能扫描页返回', '6返回'),
    ('r320', 'network_scan_back', 'Network Traffic功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r320', 'network_scan_end', 'Network Traffic:功能扫描动画后', '4首页进二级页'),
    ('r320', 'notif_clean_int', '“notification cleaner”功能：清理通知后的插页', '5功能使用完成'),
    ('r320', 'notif_scan_anim', '“notification cleaner”功能：进入功能功能扫描动画后', '5功能使用完成'),
    ('r320', 'notif_scan_back', '“notification cleaner”功能：清理通知扫描页返回', '6返回'),
    ('r320', 'screenshot_clean_back', 'Screenshot Cleaner功能：清理扫描页返回', '6返回'),
    ('r320', 'screenshot_finish', 'Screenshot Cleaner:清理完成页后（success页面后）', '4首页进二级页'),
    ('r320', 'screenshot_func_back', 'Screenshot Cleaner功能：功能扫描页返回', '6返回'),
    ('r320', 'screenshot_scan_end', 'Screenshot Cleaner:功能扫描动画后', '5功能使用完成'),
    ('r320', 'speaker_cant_wait_int', '"speaker cleaner"功能：点击“cant wait“后的插页or时间清理时间已到', '5功能使用完成'),
    ('r320', 'speaker_scan_back', '"speaker cleaner"功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r320b', 'all', 'ALL', 'ALL'),
    ('r320b', 'appman_delete_back', 'App Manager功能：删除app扫描页返回', '6返回'),
    ('r320b', 'appman_func_back', 'App Manager功能：功能扫描页返回', '6返回'),
    ('r320b', 'appman_scan_end', 'App Manager：卸载app完成页后（success页面后）', '5功能使用完成'),
    ('r320b', 'battery_finish', '“Battery info”功能：完成页后（success页）', '4首页进二级页'),
    ('r320b', 'battery_func_back', 'Battery info”功能：功能扫描页返回', '6返回'),
    ('r320b', 'battery_scan_back', 'Battery info”功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r320b', 'battery_scan_int', '“Battery info”功能：扫描动画页后插页', '5功能使用完成'),
    ('r320b', 'cache_clean_back', '“Remove Cache”功能：清理扫描页返回', '6返回'),
    ('r320b', 'cache_clean_int', '“Remove Cache”功能：删除垃圾动画后插页or从垃圾信息页返回', '6返回'),
    ('r320b', 'cache_func_back', '“Remove Cache”功能：功能扫描页返回', '6返回'),
    ('r320b', 'cache_scan_anim', 'Clean Cache：功能扫描动画后', '4首页进二级页'),
    ('r320b', 'cold_open', '1非首次冷启动', '1冷启动'),
    ('r320b', 'dup_clean_back', '"Duplicate clean"功能：清理扫描页返回', '6返回'),
    ('r320b', 'dup_finish', '"Duplicate clean"功能：完成页后', '4首页进二级页'),
    ('r320b', 'dup_func_back', '"Duplicate clean"功能：功能扫描页返回', '6返回'),
    ('r320b', 'dup_scan_int', 'Large File Cleaner：功能扫描动画后', '4首页进二级页'),
    ('r320b', 'first_clean_finish', '首次启动，清理完成动画页后，（包括不同意授权返回）', '4首页进二级页'),
    ('r320b', 'first_cold_open', '1首次冷启动', '1冷启动'),
    ('r320b', 'first_express_clean', '5新手电池点清理', '5功能使用完成'),
    ('r320b', 'first_scan_anim', '3新手扫描完成', '4首页进二级页'),
    ('r320b', 'hot_open', '2热启动', '2热启动'),
    ('r320b', 'junk_clean_back', 'Junk clean”功能：清理扫描页返回', '6返回'),
    ('r320b', 'junk_clean_int', '“Junk clean”功能：清理完成后插页or垃圾信息页点击返回后插页', '6返回'),
    ('r320b', 'junk_finish', '“Junk clean”功能：完成页后', '5功能使用完成'),
    ('r320b', 'junk_func_back', 'Junk clean”功能：功能扫描页返回', '6返回'),
    ('r320b', 'junk_scan_end', '“Junk clean”功能：功能进入对应功能扫描页扫描结束', '4首页进二级页'),
    ('r320b', 'large_clean_back', 'Large File Cleaner功能：清理扫描页返回', '6返回'),
    ('r320b', 'large_finish', 'Large File Cleaner：清理完成页后（success页面后）', '5功能使用完成'),
    ('r320b', 'large_func_back', 'Large File Cleaner功能：功能扫描页返回', '6返回'),
    ('r320b', 'memory_finish', '“Memory info”功能：完成页后', '4首页进二级页'),
    ('r320b', 'memory_func_back', '“Memory info”功能：功能扫描页返回', '6返回'),
    ('r320b', 'memory_scan_back', '“Memory info”功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r320b', 'memory_scan_int', '“Memory info”功能：扫描动画页后插页', '6返回'),
    ('r320b', 'network_finish', 'Network Traffic功能：完成页后', '5功能使用完成'),
    ('r320b', 'network_func_back', 'Network Traffic功能：功能扫描页返回', '6返回'),
    ('r320b', 'network_scan_back', 'Network Traffic功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r320b', 'network_scan_end', 'Network Traffic:功能扫描动画后', '4首页进二级页'),
    ('r320b', 'notif_clean_int', '“notification cleaner”功能：清理通知后的插页', '5功能使用完成'),
    ('r320b', 'notif_scan_anim', '“notification cleaner”功能：进入功能功能扫描动画后', '5功能使用完成'),
    ('r320b', 'notif_scan_back', '“notification cleaner”功能：清理通知扫描页返回', '6返回'),
    ('r320b', 'screenshot_clean_back', 'Screenshot Cleaner功能：清理扫描页返回', '6返回'),
    ('r320b', 'screenshot_finish', 'Screenshot Cleaner:清理完成页后（success页面后）', '4首页进二级页'),
    ('r320b', 'screenshot_func_back', 'Screenshot Cleaner功能：功能扫描页返回', '6返回'),
    ('r320b', 'screenshot_scan_end', 'Screenshot Cleaner:功能扫描动画后', '5功能使用完成'),
    ('r320b', 'speaker_cant_wait_int', '"speaker cleaner"功能：点击“cant wait“后的插页or时间清理时间已到', '5功能使用完成'),
    ('r320b', 'speaker_scan_back', '"speaker cleaner"功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r321', 'all', 'ALL', 'ALL'),
    ('r321', 'beforerepo', '4进入报告页', '4首页进二级页'),
    ('r321', 'beforeres', '6功能使用完成', '5功能使用完成'),
    ('r321', 'colwitch', '1冷启动', '1冷启动'),
    ('r321', 'firwitch', '5新手电池点清理', '5功能使用完成'),
    ('r321', 'howitch', '2热启动', '2热启动'),
    ('r321b', 'all', 'ALL', 'ALL'),
    ('r321b', 'beforerepo', '4进入报告页', '4首页进二级页'),
    ('r321b', 'beforeres', '6功能使用完成', '5功能使用完成'),
    ('r321b', 'colwitch', '1冷启动', '1冷启动'),
    ('r321b', 'firwitch', '5新手电池点清理', '5功能使用完成'),
    ('r321b', 'howitch', '2热启动', '2热启动'),
    ('r322', 'all', 'ALL', 'ALL'),
    ('r322', 'app_manager_back', 'App Manager返回', '6返回'),
    ('r322', 'app_manager_finish', 'App Manager：卸载app完成页后（success页面后）', '5功能使用完成'),
    ('r322', 'app_manager_scan_int', 'App Manager：功能扫描动画后', '4首页进二级页'),
    ('r322', 'battery_back', '“Battery info”返回', '6返回'),
    ('r322', 'battery_finish', '“Battery info”功能：完成页后（success页）', '4首页进二级页'),
    ('r322', 'battery_scan_int', '“Battery info”功能：扫描动画页后插页', '5功能使用完成'),
    ('r322', 'cache_back', 'Clean Cache返回', '6返回'),
    ('r322', 'cache_clean_int', 'Clean Cache：功能扫描动画后', '4首页进二级页'),
    ('r322', 'cache_finish', 'Clean Cache：清理完成页后（success页面后）', '5功能使用完成'),
    ('r322', 'cold_open', '1非首次冷启动', '1冷启动'),
    ('r322', 'first_cold_open', '1首次冷启动', '1冷启动'),
    ('r322', 'first_scan_anim', '3新手扫描完成', '4首页进二级页'),
    ('r322', 'first_smart_clean_tap', '5新手电池点清理', '5功能使用完成'),
    ('r322', 'hot_open', '2热启动', '2热启动'),
    ('r322', 'large_file_back', 'large file Cleaner返回', '6返回'),
    ('r322', 'large_file_finish', 'Large File Cleaner：清理完成页后（success页面后）', '5功能使用完成'),
    ('r322', 'large_file_scan_int', 'Large File Cleaner：功能扫描动画后', '4首页进二级页'),
    ('r322', 'network_back', '"Network Traffic"返回', '6返回'),
    ('r322', 'network_scan_int', 'Network Traffic:功能扫描动画后', '4首页进二级页'),
    ('r322', 'notif_back', '“notification cleaner”返回', '6返回'),
    ('r322', 'notif_clean_int', '“notification cleaner”功能：清理通知后的插页', '5功能使用完成'),
    ('r322', 'notif_func_anim', '“notification cleaner”功能：功能动画页后', '4首页进二级页'),
    ('r322', 'photos_back', 'photos返回', '6返回'),
    ('r322', 'photos_finish', 'Similar Photos:清理完成页后（success页面后）', '4首页进二级页'),
    ('r322', 'photos_scan_int', 'Similar Photos:功能扫描动画后', '5功能使用完成'),
    ('r322', 'ram_back', '“RAM Status”返回', '6返回'),
    ('r322', 'ram_finish', '“RAM Status”：完成页后', '4首页进二级页'),
    ('r322', 'ram_scan_int', '“RAM Status”：扫描动画页后插页', '5功能使用完成'),
    ('r322', 'speaker_back', '"speaker cleaner"返回', '6返回'),
    ('r322', 'speaker_cant_wait_int', '"speaker cleaner"功能：点击“cant wait“后的插页or时间清理时间已到', '5功能使用完成'),
    ('r322b', 'all', 'ALL', 'ALL'),
    ('r322b', 'app_manager_back', 'App Manager返回', '6返回'),
    ('r322b', 'app_manager_finish', 'App Manager：卸载app完成页后（success页面后）', '5功能使用完成'),
    ('r322b', 'app_manager_scan_int', 'App Manager：功能扫描动画后', '4首页进二级页'),
    ('r322b', 'battery_back', '“Battery info”返回', '6返回'),
    ('r322b', 'battery_finish', '“Battery info”功能：完成页后（success页）', '4首页进二级页'),
    ('r322b', 'battery_scan_int', '“Battery info”功能：扫描动画页后插页', '5功能使用完成'),
    ('r322b', 'cache_back', 'Clean Cache返回', '6返回'),
    ('r322b', 'cache_clean_int', 'Clean Cache：功能扫描动画后', '4首页进二级页'),
    ('r322b', 'cache_finish', 'Clean Cache：清理完成页后（success页面后）', '5功能使用完成'),
    ('r322b', 'cold_open', '1非首次冷启动', '1冷启动'),
    ('r322b', 'first_cold_open', '1首次冷启动', '1冷启动'),
    ('r322b', 'first_scan_anim', '3新手扫描完成', '4首页进二级页'),
    ('r322b', 'first_smart_clean_tap', '5新手电池点清理', '5功能使用完成'),
    ('r322b', 'hot_open', '2热启动', '2热启动'),
    ('r322b', 'large_file_back', 'large file Cleaner返回', '6返回'),
    ('r322b', 'large_file_finish', 'Large File Cleaner：清理完成页后（success页面后）', '5功能使用完成'),
    ('r322b', 'large_file_scan_int', 'Large File Cleaner：功能扫描动画后', '4首页进二级页'),
    ('r322b', 'network_back', '"Network Traffic"返回', '6返回'),
    ('r322b', 'network_scan_int', 'Network Traffic:功能扫描动画后', '4首页进二级页'),
    ('r322b', 'notif_back', '“notification cleaner”返回', '6返回'),
    ('r322b', 'notif_clean_int', '“notification cleaner”功能：清理通知后的插页', '5功能使用完成'),
    ('r322b', 'notif_func_anim', '“notification cleaner”功能：功能动画页后', '4首页进二级页'),
    ('r322b', 'photos_back', 'photos返回', '6返回'),
    ('r322b', 'photos_finish', 'Similar Photos:清理完成页后（success页面后）', '4首页进二级页'),
    ('r322b', 'photos_scan_int', 'Similar Photos:功能扫描动画后', '5功能使用完成'),
    ('r322b', 'ram_back', '“RAM Status”返回', '6返回'),
    ('r322b', 'ram_finish', '“RAM Status”：完成页后', '4首页进二级页'),
    ('r322b', 'ram_scan_int', '“RAM Status”：扫描动画页后插页', '5功能使用完成'),
    ('r322b', 'speaker_back', '"speaker cleaner"返回', '6返回'),
    ('r322b', 'speaker_cant_wait_int', '"speaker cleaner"功能：点击“cant wait“后的插页or时间清理时间已到', '5功能使用完成'),
    ('r324', 'all', 'ALL', 'ALL'),
    ('r324', 'appman_delete_back', 'App Manager功能：删除app扫描页返回', '6返回'),
    ('r324', 'appman_func_back', 'App Manager功能：功能扫描页返回', '6返回'),
    ('r324', 'appman_scan_end', 'App Manager：卸载app完成页后（success页面后）', '5功能使用完成'),
    ('r324', 'battery_finish', '“Battery info”功能：完成页后（success页）', '4首页进二级页'),
    ('r324', 'battery_func_back', 'Battery info”功能：功能扫描页返回', '6返回'),
    ('r324', 'battery_scan_back', 'Battery info”功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r324', 'battery_scan_int', '“Battery info”功能：扫描动画页后插页', '5功能使用完成'),
    ('r324', 'cache_clean_back', '“Remove Cache”功能：清理扫描页返回', '6返回'),
    ('r324', 'cache_clean_int', '“Remove Cache”功能：删除垃圾动画后插页or从垃圾信息页返回', '6返回'),
    ('r324', 'cache_func_back', '“Remove Cache”功能：功能扫描页返回', '6返回'),
    ('r324', 'cache_scan_anim', 'Clean Cache：功能扫描动画后', '4首页进二级页'),
    ('r324', 'cold_open', '1非首次冷启动', '1冷启动'),
    ('r324', 'dup_clean_back', '"Duplicate clean"功能：清理扫描页返回', '6返回'),
    ('r324', 'dup_finish', '"Duplicate clean"功能：完成页后', '4首页进二级页'),
    ('r324', 'dup_func_back', '"Duplicate clean"功能：功能扫描页返回', '6返回'),
    ('r324', 'dup_scan_int', 'Large File Cleaner：功能扫描动画后', '4首页进二级页'),
    ('r324', 'first_cold_open', '1首次冷启动', '1冷启动'),
    ('r324', 'first_express_clean', '5新手电池点清理', '5功能使用完成'),
    ('r324', 'first_scan_anim', '3新手扫描完成', '4首页进二级页'),
    ('r324', 'hot_open', '2热启动', '2热启动'),
    ('r324', 'junk_clean_back', 'Junk clean”功能：清理扫描页返回', '6返回'),
    ('r324', 'junk_clean_int', '“Junk clean”功能：清理完成后插页or垃圾信息页点击返回后插页', '6返回'),
    ('r324', 'junk_finish', '“Junk clean”功能：完成页后', '5功能使用完成'),
    ('r324', 'junk_func_back', 'Junk clean”功能：功能扫描页返回', '6返回'),
    ('r324', 'junk_scan_end', '“Junk clean”功能：功能进入对应功能扫描页扫描结束', '4首页进二级页'),
    ('r324', 'large_clean_back', 'Large File Cleaner功能：清理扫描页返回', '6返回'),
    ('r324', 'large_finish', 'Large File Cleaner：清理完成页后（success页面后）', '5功能使用完成'),
    ('r324', 'large_func_back', 'Large File Cleaner功能：功能扫描页返回', '6返回'),
    ('r324', 'memory_finish', '“Memory info”功能：完成页后', '4首页进二级页'),
    ('r324', 'memory_func_back', '“Memory info”功能：功能扫描页返回', '6返回'),
    ('r324', 'memory_scan_back', '“Memory info”功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r324', 'memory_scan_int', '“Memory info”功能：扫描动画页后插页', '6返回'),
    ('r324', 'network_finish', 'Network Traffic功能：完成页后', '5功能使用完成'),
    ('r324', 'network_func_back', 'Network Traffic功能：功能扫描页返回', '6返回'),
    ('r324', 'network_scan_back', 'Network Traffic功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r324', 'network_scan_end', 'Network Traffic:功能扫描动画后', '4首页进二级页'),
    ('r324', 'notif_clean_int', '“notification cleaner”功能：清理通知后的插页', '5功能使用完成'),
    ('r324', 'notif_scan_anim', '“notification cleaner”功能：进入功能功能扫描动画后', '5功能使用完成'),
    ('r324', 'notif_scan_back', '“notification cleaner”功能：清理通知扫描页返回', '6返回'),
    ('r324', 'screenshot_clean_back', 'Screenshot Cleaner功能：清理扫描页返回', '6返回'),
    ('r324', 'screenshot_finish', 'Screenshot Cleaner:清理完成页后（success页面后）', '4首页进二级页'),
    ('r324', 'screenshot_func_back', 'Screenshot Cleaner功能：功能扫描页返回', '6返回'),
    ('r324', 'screenshot_scan_end', 'Screenshot Cleaner:功能扫描动画后', '5功能使用完成'),
    ('r324', 'speaker_cant_wait_int', '"speaker cleaner"功能：点击“cant wait“后的插页or时间清理时间已到', '5功能使用完成'),
    ('r324', 'speaker_scan_back', '"speaker cleaner"功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r324b', 'all', 'ALL', 'ALL'),
    ('r324b', 'appman_delete_back', 'App Manager功能：删除app扫描页返回', '6返回'),
    ('r324b', 'appman_func_back', 'App Manager功能：功能扫描页返回', '6返回'),
    ('r324b', 'appman_scan_end', 'App Manager：卸载app完成页后（success页面后）', '5功能使用完成'),
    ('r324b', 'battery_finish', '“Battery info”功能：完成页后（success页）', '4首页进二级页'),
    ('r324b', 'battery_func_back', 'Battery info”功能：功能扫描页返回', '6返回'),
    ('r324b', 'battery_scan_back', 'Battery info”功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r324b', 'battery_scan_int', '“Battery info”功能：扫描动画页后插页', '5功能使用完成'),
    ('r324b', 'cache_clean_back', '“Remove Cache”功能：清理扫描页返回', '6返回'),
    ('r324b', 'cache_clean_int', '“Remove Cache”功能：删除垃圾动画后插页or从垃圾信息页返回', '6返回'),
    ('r324b', 'cache_func_back', '“Remove Cache”功能：功能扫描页返回', '6返回'),
    ('r324b', 'cache_scan_anim', 'Clean Cache：功能扫描动画后', '4首页进二级页'),
    ('r324b', 'cold_open', '1非首次冷启动', '1冷启动'),
    ('r324b', 'dup_clean_back', '"Duplicate clean"功能：清理扫描页返回', '6返回'),
    ('r324b', 'dup_finish', '"Duplicate clean"功能：完成页后', '4首页进二级页'),
    ('r324b', 'dup_func_back', '"Duplicate clean"功能：功能扫描页返回', '6返回'),
    ('r324b', 'dup_scan_int', 'Large File Cleaner：功能扫描动画后', '4首页进二级页'),
    ('r324b', 'first_cold_open', '1首次冷启动', '1冷启动'),
    ('r324b', 'first_express_clean', '5新手电池点清理', '5功能使用完成'),
    ('r324b', 'first_scan_anim', '3新手扫描完成', '4首页进二级页'),
    ('r324b', 'hot_open', '2热启动', '2热启动'),
    ('r324b', 'junk_clean_back', 'Junk clean”功能：清理扫描页返回', '6返回'),
    ('r324b', 'junk_clean_int', '“Junk clean”功能：清理完成后插页or垃圾信息页点击返回后插页', '6返回'),
    ('r324b', 'junk_finish', '“Junk clean”功能：完成页后', '5功能使用完成'),
    ('r324b', 'junk_func_back', 'Junk clean”功能：功能扫描页返回', '6返回'),
    ('r324b', 'junk_scan_end', '“Junk clean”功能：功能进入对应功能扫描页扫描结束', '4首页进二级页'),
    ('r324b', 'large_clean_back', 'Large File Cleaner功能：清理扫描页返回', '6返回'),
    ('r324b', 'large_finish', 'Large File Cleaner：清理完成页后（success页面后）', '5功能使用完成'),
    ('r324b', 'large_func_back', 'Large File Cleaner功能：功能扫描页返回', '6返回'),
    ('r324b', 'memory_finish', '“Memory info”功能：完成页后', '4首页进二级页'),
    ('r324b', 'memory_func_back', '“Memory info”功能：功能扫描页返回', '6返回'),
    ('r324b', 'memory_scan_back', '“Memory info”功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r324b', 'memory_scan_int', '“Memory info”功能：扫描动画页后插页', '6返回'),
    ('r324b', 'network_finish', 'Network Traffic功能：完成页后', '5功能使用完成'),
    ('r324b', 'network_func_back', 'Network Traffic功能：功能扫描页返回', '6返回'),
    ('r324b', 'network_scan_back', 'Network Traffic功能：进入完成页之前的扫描动画返回', '6返回'),
    ('r324b', 'network_scan_end', 'Network Traffic:功能扫描动画后', '4首页进二级页'),
    ('r324b', 'notif_clean_int', '“notification cleaner”功能：清理通知后的插页', '5功能使用完成'),
    ('r324b', 'notif_scan_anim', '“notification cleaner”功能：进入功能功能扫描动画后', '5功能使用完成'),
    ('r324b', 'notif_scan_back', '“notification cleaner”功能：清理通知扫描页返回', '6返回'),
    ('r324b', 'screenshot_clean_back', 'Screenshot Cleaner功能：清理扫描页返回', '6返回'),
    ('r324b', 'screenshot_finish', 'Screenshot Cleaner:清理完成页后（success页面后）', '4首页进二级页'),
    ('r324b', 'screenshot_func_back', 'Screenshot Cleaner功能：功能扫描页返回', '6返回'),
    ('r324b', 'screenshot_scan_end', 'Screenshot Cleaner:功能扫描动画后', '5功能使用完成'),
    ('r324b', 'speaker_cant_wait_int', '"speaker cleaner"功能：点击“cant wait“后的插页or时间清理时间已到', '5功能使用完成'),
    ('r324b', 'speaker_scan_back', '"speaker cleaner"功能：进入完成页之前的扫描动画返回', '6返回'),
    ('rl01b', 'all', 'ALL', 'ALL'),
    ('rl01b', 'tc_aban', '19邀请追踪器底部原生', '8二级页原生'),
    ('rl01b', 'tc_adbvu', '25首页点击add friends后全屏广告', '4首页进二级页'),
    ('rl01b', 'tc_bacbs', '5返回', '6返回'),
    ('rl01b', 'tc_bftck', '9追踪用户明细点击历史', '5功能使用完成'),
    ('rl01b', 'tc_codlv', '1冷启动', '1冷启动'),
    ('rl01b', 'tc_cosvc', '8创建地理围栏成功插屏', '5功能使用完成'),
    ('rl01b', 'tc_gubcl', '3新手插屏', '3新手插屏'),
    ('rl01b', 'tc_gupg', '15新手引导原生广告', '7新手原生'),
    ('rl01b', 'tc_hban', '11首页底部banner', '首页banner'),
    ('rl01b', 'tc_htdlv', '2热启动', '2热启动'),
    ('rl01b', 'tc_lafkc', '13语言页原生广告', '7新手原生'),
    ('rl01b', 'tc_nbtcdn', '6电话号码搜索结果插屏', '5功能使用完成'),
    ('rl01b', 'tc_nbtkd', '28首页点击Number Trcker后全屏广告', '4首页进二级页'),
    ('rl01b', 'tc_pban', '17首页权限弹窗引导底部原生', '8二级页原生'),
    ('rl01b', 'tc_rebcj', '31点击刷新my friends的设备进入朋友位置页面前全屏广告', '8二级页原生'),
    ('rl01b', 'tc_sban', '18我有邀请码页底部原生', '8二级页原生'),
    ('rl01b', 'tc_sebks', '27首页点击set zone后全屏广告', '4首页进二级页'),
    ('rl01b', 'tc_shvia', '26首页点击share location后全屏广告', '4首页进二级页'),
    ('rl01b', 'tc_stts', '21设置页原生（如何使用和电话号码之间）', '8二级页原生'),
    ('rl01b', 'tc_tckmd', '23追踪用户详情页原生', '8二级页原生'),
    ('rl01b', 'tc_tu1ks', '29点击Tutorials的locate my friends后页面中部信息流原生', '8二级页原生'),
    ('rl01b', 'tc_tu2ks', '30点击Tutorials的share my location后页面中部信息流原生', '8二级页原生'),
    ('rl01b', 'tc_vicbv', '24首页点击view real-time location后全屏广告', '4首页进二级页'),
    ('rl01b', 'tc_zlogmd', '20围栏页顶部部原生', '8二级页原生'),
    ('rl01c', 'all', 'ALL', 'ALL'),
    ('rl01c', 'tc_aban', '19邀请追踪器底部原生', '8二级页原生'),
    ('rl01c', 'tc_adbvu', '25首页点击add friends后全屏广告', '4首页进二级页'),
    ('rl01c', 'tc_bacbs', '5返回', '6返回'),
    ('rl01c', 'tc_bftck', '9追踪用户明细点击历史', '5功能使用完成'),
    ('rl01c', 'tc_codlv', '1冷启动', '1冷启动'),
    ('rl01c', 'tc_cosvc', '8创建地理围栏成功插屏', '5功能使用完成'),
    ('rl01c', 'tc_gubcl', '3新手插屏', '3新手插屏'),
    ('rl01c', 'tc_gupg', '15新手引导原生广告', '7新手原生'),
    ('rl01c', 'tc_hban', '11首页底部banner', '首页banner'),
    ('rl01c', 'tc_htdlv', '2热启动', '2热启动'),
    ('rl01c', 'tc_lafkc', '13语言页原生广告', '7新手原生'),
    ('rl01c', 'tc_nbtcdn', '6电话号码搜索结果插屏', '5功能使用完成'),
    ('rl01c', 'tc_nbtkd', '28首页点击Number Trcker后全屏广告', '4首页进二级页'),
    ('rl01c', 'tc_pban', '17首页权限弹窗引导底部原生', '8二级页原生'),
    ('rl01c', 'tc_rebcj', '31点击刷新my friends的设备进入朋友位置页面前全屏广告', '8二级页原生'),
    ('rl01c', 'tc_sban', '18我有邀请码页底部原生', '8二级页原生'),
    ('rl01c', 'tc_sebks', '27首页点击set zone后全屏广告', '4首页进二级页'),
    ('rl01c', 'tc_shvia', '26首页点击share location后全屏广告', '4首页进二级页'),
    ('rl01c', 'tc_stts', '21设置页原生（如何使用和电话号码之间）', '8二级页原生'),
    ('rl01c', 'tc_tckmd', '23追踪用户详情页原生', '8二级页原生'),
    ('rl01c', 'tc_tu1ks', '29点击Tutorials的locate my friends后页面中部信息流原生', '8二级页原生'),
    ('rl01c', 'tc_tu2ks', '30点击Tutorials的share my location后页面中部信息流原生', '8二级页原生'),
    ('rl01c', 'tc_vicbv', '24首页点击view real-time location后全屏广告', '4首页进二级页'),
    ('rl01c', 'tc_zlogmd', '20围栏页顶部部原生', '8二级页原生'),
    ('rm04b', 'albbmint', '4专辑插屏', '4首页进二级页'),
    ('rm04b', 'albummnav', '20专辑原生', '专辑原生'),
    ('rm04b', 'all', 'ALL', 'ALL'),
    ('rm04b', 'artieint', '6歌手插屏', '4首页进二级页'),
    ('rm04b', 'artisttnav', '18歌手原生', '歌手原生'),
    ('rm04b', 'backint', '13返回', '6返回'),
    ('rm04b', 'creatint', '10自建&收藏歌单', '4首页进二级页'),
    ('rm04b', 'downloint', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm04b', 'frontpagenav', '17首页原生', '首页原生'),
    ('rm04b', 'gennint', '7流派插屏', '4首页进二级页'),
    ('rm04b', 'hoto', '2热启动', '2热启动'),
    ('rm04b', 'lllistint', '5歌单插屏', '4首页进二级页'),
    ('rm04b', 'lllistnav', '19歌单原生', '歌单原生'),
    ('rm04b', 'ocold', '1冷启动', '1冷启动'),
    ('rm04b', 'playingint', '16歌曲下载', '7歌曲下载'),
    ('rm04b', 'playnextint', '14切歌', '9切歌'),
    ('rm04b', 'redhint', '8红心歌单', '4首页进二级页'),
    ('rm04b', 'scanint', '12点击搜索', '8搜索'),
    ('rm04b', 'seachhnav', '22搜索原生', '搜索原生'),
    ('rm04b', 'songplay', '15歌曲播放', '5歌曲播放'),
    ('rm04b', 'startint', '3新手插屏', '3新手插屏'),
    ('rm04b', 'videoint', '11MV播放页', '切换MV播放'),
    ('rm04c', 'albbmint', '4专辑插屏', '4首页进二级页'),
    ('rm04c', 'albummnav', '20专辑原生', '专辑原生'),
    ('rm04c', 'all', 'ALL', 'ALL'),
    ('rm04c', 'artieint', '6歌手插屏', '4首页进二级页'),
    ('rm04c', 'artisttnav', '18歌手原生', '歌手原生'),
    ('rm04c', 'backint', '13返回', '6返回'),
    ('rm04c', 'creatint', '10自建&收藏歌单', '4首页进二级页'),
    ('rm04c', 'downloint', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm04c', 'frontpagenav', '17首页原生', '首页原生'),
    ('rm04c', 'gennint', '7流派插屏', '4首页进二级页'),
    ('rm04c', 'hoto', '2热启动', '2热启动'),
    ('rm04c', 'lllistint', '5歌单插屏', '4首页进二级页'),
    ('rm04c', 'lllistnav', '19歌单原生', '歌单原生'),
    ('rm04c', 'ocold', '1冷启动', '1冷启动'),
    ('rm04c', 'playingint', '16歌曲下载', '7歌曲下载'),
    ('rm04c', 'playnextint', '14切歌', '9切歌'),
    ('rm04c', 'redhint', '8红心歌单', '4首页进二级页'),
    ('rm04c', 'scanint', '12点击搜索', '8搜索'),
    ('rm04c', 'seachhnav', '22搜索原生', '搜索原生'),
    ('rm04c', 'songplay', '15歌曲播放', '5歌曲播放'),
    ('rm04c', 'startint', '3新手插屏', '3新手插屏'),
    ('rm04c', 'videoint', '11MV播放页', '切换MV播放'),
    ('rm06a', 'albcp', '4专辑插屏', '4首页进二级页'),
    ('rm06a', 'all', 'ALL', 'ALL'),
    ('rm06a', 'bkcp', '13返回', '6返回'),
    ('rm06a', 'cl_open', '1冷启动', '1冷启动'),
    ('rm06a', 'cscp', '25点控制台', '5歌曲播放'),
    ('rm06a', 'ho_open', '2热启动', '2热启动'),
    ('rm06a', 'jclcp', '10自建&收藏歌单', '4首页进二级页'),
    ('rm06a', 'lkcp', '8红心歌单', '4首页进二级页'),
    ('rm06a', 'ngdcp', '3新手插屏', '3新手插屏'),
    ('rm06a', 'offlcp', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm06a', 'rkgcp', '5歌单插屏', '4首页进二级页'),
    ('rm06a', 'searcp', '12点击搜索', '8搜索'),
    ('rm06a', 'secp', '6歌手插屏', '4首页进二级页'),
    ('rm06a', 'skpcp', '14切歌', '9切歌'),
    ('rm06a', 'splcp', '15歌曲播放', '5歌曲播放'),
    ('rm06a', 'stccp', '7流派插屏', '4首页进二级页'),
    ('rm06a', 'xzcp', '16歌曲下载', '7歌曲下载'),
    ('rm06b', 'albcp', '4专辑插屏', '4首页进二级页'),
    ('rm06b', 'all', 'ALL', 'ALL'),
    ('rm06b', 'bkcp', '13返回', '6返回'),
    ('rm06b', 'cl_open', '1冷启动', '1冷启动'),
    ('rm06b', 'cscp', '25点控制台', '5歌曲播放'),
    ('rm06b', 'ho_open', '2热启动', '2热启动'),
    ('rm06b', 'jclcp', '10自建&收藏歌单', '4首页进二级页'),
    ('rm06b', 'lkcp', '8红心歌单', '4首页进二级页'),
    ('rm06b', 'ngdcp', '3新手插屏', '3新手插屏'),
    ('rm06b', 'offlcp', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm06b', 'rkgcp', '5歌单插屏', '4首页进二级页'),
    ('rm06b', 'searcp', '12点击搜索', '8搜索'),
    ('rm06b', 'secp', '6歌手插屏', '4首页进二级页'),
    ('rm06b', 'skpcp', '14切歌', '9切歌'),
    ('rm06b', 'splcp', '15歌曲播放', '5歌曲播放'),
    ('rm06b', 'stccp', '7流派插屏', '4首页进二级页'),
    ('rm06b', 'xzcp', '16歌曲下载', '7歌曲下载'),
    ('rm07', 'all', 'ALL', 'ALL'),
    ('rm07', 'bdzyint', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm07', 'fhint', '13返回', '6返回'),
    ('rm07', 'gsint', '6歌手插屏', '4首页进二级页'),
    ('rm07', 'hxint', '8红心歌单', '4首页进二级页'),
    ('rm07', 'jilirw', '16歌曲下载', '7歌曲下载'),
    ('rm07', 'lenopen', '1冷启动', '1冷启动'),
    ('rm07', 'lpint', '7流派插屏', '4首页进二级页'),
    ('rm07', 'lqzzbfint', '15歌曲播放', '5歌曲播放'),
    ('rm07', 'lxdjint', '14切歌', '9切歌'),
    ('rm07', 'phbint', '5歌单插屏', '4首页进二级页'),
    ('rm07', 'playmvint', '11MV播放页', '切换MV播放'),
    ('rm07', 'reopen', '2热启动', '2热启动'),
    ('rm07', 'ssjgint', '12点击搜索', '8搜索'),
    ('rm07', 'ydint', '3新手插屏', '3新手插屏'),
    ('rm07', 'zjgdint', '10自建&收藏歌单', '4首页进二级页'),
    ('rm07', 'zjint', '4专辑插屏', '4首页进二级页'),
    ('rm07b', 'all', 'ALL', 'ALL'),
    ('rm07b', 'bdzyint', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm07b', 'fhint', '13返回', '6返回'),
    ('rm07b', 'gsint', '6歌手插屏', '4首页进二级页'),
    ('rm07b', 'hxint', '8红心歌单', '4首页进二级页'),
    ('rm07b', 'jilirw', '16歌曲下载', '7歌曲下载'),
    ('rm07b', 'lenopen', '1冷启动', '1冷启动'),
    ('rm07b', 'lpint', '7流派插屏', '4首页进二级页'),
    ('rm07b', 'lqzzbfint', '15歌曲播放', '5歌曲播放'),
    ('rm07b', 'lxdjint', '14切歌', '9切歌'),
    ('rm07b', 'lynav', '23语言页原生', '7新手原生'),
    ('rm07b', 'phbint', '5歌单插屏', '4首页进二级页'),
    ('rm07b', 'playmvint', '11MV播放页', '切换MV播放'),
    ('rm07b', 'recplaylist', '21最近播放原生', '最近播放原生'),
    ('rm07b', 'reopen', '2热启动', '2热启动'),
    ('rm07b', 'ssjgint', '12点击搜索', '8搜索'),
    ('rm07b', 'ydint', '3新手插屏', '3新手插屏'),
    ('rm07b', 'zjgdint', '10自建&收藏歌单', '4首页进二级页'),
    ('rm07b', 'zjint', '4专辑插屏', '4首页进二级页'),
    ('rm08', 'all', 'ALL', 'ALL'),
    ('rm08', 'ccopen', '1冷启动', '1冷启动'),
    ('rm08', 'hhopen', '2热启动', '2热启动'),
    ('rm08', 'insabb', '4专辑插屏', '4首页进二级页'),
    ('rm08', 'insatt', '6歌手插屏', '4首页进二级页'),
    ('rm08', 'insback', '13返回', '6返回'),
    ('rm08', 'inscon', '25点控制台', '5歌曲播放'),
    ('rm08', 'inscret', '10自建&收藏歌单', '4首页进二级页'),
    ('rm08', 'insdown', '16歌曲下载', '7歌曲下载'),
    ('rm08', 'inshg', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm08', 'insnewgd', '3新手插屏', '3新手插屏'),
    ('rm08', 'inspa', '7流派插屏', '4首页进二级页'),
    ('rm08', 'insplayn', '14切歌', '9切歌'),
    ('rm08', 'insred', '8红心歌单', '4首页进二级页'),
    ('rm08', 'insrrr', '5歌单插屏', '4首页进二级页'),
    ('rm08', 'inssec', '12点击搜索', '8搜索'),
    ('rm08', 'inssp', '15歌曲播放', '5歌曲播放'),
    ('rm08b', 'all', 'ALL', 'ALL'),
    ('rm08b', 'ccopen', '1冷启动', '1冷启动'),
    ('rm08b', 'hhopen', '2热启动', '2热启动'),
    ('rm08b', 'insabb', '4专辑插屏', '4首页进二级页'),
    ('rm08b', 'insatt', '6歌手插屏', '4首页进二级页'),
    ('rm08b', 'insback', '13返回', '6返回'),
    ('rm08b', 'inscon', '25点控制台', '5歌曲播放'),
    ('rm08b', 'inscret', '10自建&收藏歌单', '4首页进二级页'),
    ('rm08b', 'insdown', '16歌曲下载', '7歌曲下载'),
    ('rm08b', 'inshg', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm08b', 'insnewgd', '3新手插屏', '3新手插屏'),
    ('rm08b', 'inspa', '7流派插屏', '4首页进二级页'),
    ('rm08b', 'insplayn', '14切歌', '9切歌'),
    ('rm08b', 'insred', '8红心歌单', '4首页进二级页'),
    ('rm08b', 'insrrr', '5歌单插屏', '4首页进二级页'),
    ('rm08b', 'inssec', '12点击搜索', '8搜索'),
    ('rm08b', 'inssp', '15歌曲播放', '5歌曲播放'),
    ('rm09', 'all', 'ALL', 'ALL'),
    ('rm09', 'bckovb', '13返回', '6返回'),
    ('rm09', 'cretivb', '10自建&收藏歌单', '4首页进二级页'),
    ('rm09', 'ctovb', '1冷启动', '1冷启动'),
    ('rm09', 'dwlivb', '16歌曲下载', '7歌曲下载'),
    ('rm09', 'fovivb', '8红心歌单', '4首页进二级页'),
    ('rm09', 'gereivb', '7流派插屏', '4首页进二级页'),
    ('rm09', 'htovb', '2热启动', '2热启动'),
    ('rm09', 'laplvb', '15歌曲播放', '5歌曲播放'),
    ('rm09', 'listivb', '5歌单插屏', '4首页进二级页'),
    ('rm09', 'lngvb', '23语言页原生', '7新手原生'),
    ('rm09', 'locivb', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm09', 'mxgovb', '11MV播放页', '切换MV播放'),
    ('rm09', 'qievb', '14切歌', '9切歌'),
    ('rm09', 'rcentvb', '21最近播放原生', '最近播放原生'),
    ('rm09', 'serchsvb', '12点击搜索', '8搜索'),
    ('rm09', 'sigeivb', '6歌手插屏', '4首页进二级页'),
    ('rm09', 'ydyvb', '3新手插屏', '3新手插屏'),
    ('rm09', 'zhaivb', '4专辑插屏', '4首页进二级页'),
    ('rm09b', 'all', 'ALL', 'ALL'),
    ('rm09b', 'bckovb', '13返回', '6返回'),
    ('rm09b', 'cretivb', '10自建&收藏歌单', '4首页进二级页'),
    ('rm09b', 'ctovb', '1冷启动', '1冷启动'),
    ('rm09b', 'dwlivb', '16歌曲下载', '7歌曲下载'),
    ('rm09b', 'fovivb', '8红心歌单', '4首页进二级页'),
    ('rm09b', 'gereivb', '7流派插屏', '4首页进二级页'),
    ('rm09b', 'htovb', '2热启动', '2热启动'),
    ('rm09b', 'laplvb', '15歌曲播放', '5歌曲播放'),
    ('rm09b', 'listivb', '5歌单插屏', '4首页进二级页'),
    ('rm09b', 'lngvb', '23语言页原生', '7新手原生'),
    ('rm09b', 'locivb', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm09b', 'mxgovb', '11MV播放页', '切换MV播放'),
    ('rm09b', 'qievb', '14切歌', '9切歌'),
    ('rm09b', 'rcentvb', '21最近播放原生', '最近播放原生'),
    ('rm09b', 'serchsvb', '12点击搜索', '8搜索'),
    ('rm09b', 'sigeivb', '6歌手插屏', '4首页进二级页'),
    ('rm09b', 'ydyvb', '3新手插屏', '3新手插屏'),
    ('rm09b', 'zhaivb', '4专辑插屏', '4首页进二级页'),
    ('rm10', 'albumxq', '4专辑插屏', '4首页进二级页'),
    ('rm10', 'all', 'ALL', 'ALL'),
    ('rm10', 'closenew', '3新手插屏', '3新手插屏'),
    ('rm10', 'comeback', '13返回', '6返回'),
    ('rm10', 'consoleopen', '25点控制台', '5歌曲播放'),
    ('rm10', 'coolopen', '1冷启动', '1冷启动'),
    ('rm10', 'heartclick', '8红心歌单', '4首页进二级页'),
    ('rm10', 'hotopen', '2热启动', '2热启动'),
    ('rm10', 'listcli', '5歌单插屏', '4首页进二级页'),
    ('rm10', 'localsing', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm10', 'myselflist', '10自建&收藏歌单', '4首页进二级页'),
    ('rm10', 'resultspop', '12点击搜索', '8搜索'),
    ('rm10', 'singercli', '6歌手插屏', '4首页进二级页'),
    ('rm10', 'songbegin', '15歌曲播放', '5歌曲播放'),
    ('rm10', 'songload', '16歌曲下载', '7歌曲下载'),
    ('rm10', 'stylexq', '7流派插屏', '4首页进二级页'),
    ('rm10', 'switchsong', '14切歌', '9切歌'),
    ('rm10b', 'albumxq', '4专辑插屏', '4首页进二级页'),
    ('rm10b', 'all', 'ALL', 'ALL'),
    ('rm10b', 'closenew', '3新手插屏', '3新手插屏'),
    ('rm10b', 'comeback', '13返回', '6返回'),
    ('rm10b', 'consoleopen', '25点控制台', '5歌曲播放'),
    ('rm10b', 'coolopen', '1冷启动', '1冷启动'),
    ('rm10b', 'heartclick', '8红心歌单', '4首页进二级页'),
    ('rm10b', 'hotopen', '2热启动', '2热启动'),
    ('rm10b', 'listcli', '5歌单插屏', '4首页进二级页'),
    ('rm10b', 'localsing', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm10b', 'myselflist', '10自建&收藏歌单', '4首页进二级页'),
    ('rm10b', 'resultspop', '12点击搜索', '8搜索'),
    ('rm10b', 'singercli', '6歌手插屏', '4首页进二级页'),
    ('rm10b', 'songbegin', '15歌曲播放', '5歌曲播放'),
    ('rm10b', 'songload', '16歌曲下载', '7歌曲下载'),
    ('rm10b', 'stylexq', '7流派插屏', '4首页进二级页'),
    ('rm10b', 'switchsong', '14切歌', '9切歌'),
    ('rm11b', 'albxq', '4专辑插屏', '4首页进二级页'),
    ('rm11b', 'all', 'ALL', 'ALL'),
    ('rm11b', 'baclastym', '13返回', '6返回'),
    ('rm11b', 'clopen', '1冷启动', '1冷启动'),
    ('rm11b', 'creazjgd', '10自建&收藏歌单', '4首页进二级页'),
    ('rm11b', 'dlafter', '16歌曲下载', '7歌曲下载'),
    ('rm11b', 'frontsearc', '12点击搜索', '8搜索'),
    ('rm11b', 'gdydy', '3新手插屏', '3新手插屏'),
    ('rm11b', 'genelpy', '7流派插屏', '4首页进二级页'),
    ('rm11b', 'htopen', '2热启动', '2热启动'),
    ('rm11b', 'ingplay', '15歌曲播放', '5歌曲播放'),
    ('rm11b', 'lagenv', '23语言页原生', '7新手原生'),
    ('rm11b', 'lcbdrsgd', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm11b', 'lovegd', '8红心歌单', '4首页进二级页'),
    ('rm11b', 'mxplay', '11MV播放页', '切换MV播放'),
    ('rm11b', 'playctncl', '14切歌', '9切歌'),
    ('rm11b', 'singersy', '6歌手插屏', '4首页进二级页'),
    ('rm11b', 'songlist', '5歌单插屏', '4首页进二级页'),
    ('rm11b', 'zjlistplay', '21最近播放原生', '最近播放原生'),
    ('rm12', 'albumpage', '4专辑插屏', '4首页进二级页'),
    ('rm12', 'all', 'ALL', 'ALL'),
    ('rm12', 'backturn', '13返回', '6返回'),
    ('rm12', 'bootcool', '1冷启动', '1冷启动'),
    ('rm12', 'boothot', '2热启动', '2热启动'),
    ('rm12', 'likeclick', '8红心歌单', '4首页进二级页'),
    ('rm12', 'listuser', '5歌单插屏', '4首页进二级页'),
    ('rm12', 'localmusic', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm12', 'musicinit', '16歌曲下载', '7歌曲下载'),
    ('rm12', 'musicopen', '15歌曲播放', '5歌曲播放'),
    ('rm12', 'musicswitch', '14切歌', '9切歌'),
    ('rm12', 'ownlist', '10自建&收藏歌单', '4首页进二级页'),
    ('rm12', 'panelstart', '25点控制台', '5歌曲播放'),
    ('rm12', 'popclose', '3新手插屏', '3新手插屏'),
    ('rm12', 'searchpop', '12点击搜索', '8搜索'),
    ('rm12', 'singeruser', '6歌手插屏', '4首页进二级页'),
    ('rm12', 'stylepage', '7流派插屏', '4首页进二级页'),
    ('rm12b', 'albumpage', '4专辑插屏', '4首页进二级页'),
    ('rm12b', 'all', 'ALL', 'ALL'),
    ('rm12b', 'backturn', '13返回', '6返回'),
    ('rm12b', 'bootcool', '1冷启动', '1冷启动'),
    ('rm12b', 'boothot', '2热启动', '2热启动'),
    ('rm12b', 'likeclick', '8红心歌单', '4首页进二级页'),
    ('rm12b', 'listuser', '5歌单插屏', '4首页进二级页'),
    ('rm12b', 'localmusic', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm12b', 'musicinit', '16歌曲下载', '7歌曲下载'),
    ('rm12b', 'musicopen', '15歌曲播放', '5歌曲播放'),
    ('rm12b', 'musicswitch', '14切歌', '9切歌'),
    ('rm12b', 'ownlist', '10自建&收藏歌单', '4首页进二级页'),
    ('rm12b', 'panelstart', '25点控制台', '5歌曲播放'),
    ('rm12b', 'popclose', '3新手插屏', '3新手插屏'),
    ('rm12b', 'searchpop', '12点击搜索', '8搜索'),
    ('rm12b', 'singeruser', '6歌手插屏', '4首页进二级页'),
    ('rm12b', 'stylepage', '7流派插屏', '4首页进二级页'),
    ('rm13', 'all', 'ALL', 'ALL'),
    ('rm13', 'bdzylist', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm13', 'djfhsy', '13返回', '6返回'),
    ('rm13', 'djxzad', '16歌曲下载', '7歌曲下载'),
    ('rm13', 'fiveyy', '23语言页原生', '7新手原生'),
    ('rm13', 'hxlist', '8红心歌单', '4首页进二级页'),
    ('rm13', 'jrlpy', '7流派插屏', '4首页进二级页'),
    ('rm13', 'jrmvplay', '11MV播放页', '切换MV播放'),
    ('rm13', 'jrzjlist', '10自建&收藏歌单', '4首页进二级页'),
    ('rm13', 'leopn', '1冷启动', '1冷启动'),
    ('rm13', 'lqxcad', '15歌曲播放', '5歌曲播放'),
    ('rm13', 'lxdjxad', '14切歌', '9切歌'),
    ('rm13', 'reopn', '2热启动', '2热启动'),
    ('rm13', 'singerzy', '6歌手插屏', '4首页进二级页'),
    ('rm13', 'songgd', '5歌单插屏', '4首页进二级页'),
    ('rm13', 'ssjgq', '12点击搜索', '8搜索'),
    ('rm13', 'ydyad', '3新手插屏', '3新手插屏'),
    ('rm13', 'zjbflist', '21最近播放原生', '最近播放原生'),
    ('rm13', 'zjxqy', '4专辑插屏', '4首页进二级页'),
    ('rm13b', 'all', 'ALL', 'ALL'),
    ('rm13b', 'bdzylist', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rm13b', 'djfhsy', '13返回', '6返回'),
    ('rm13b', 'djxzad', '16歌曲下载', '7歌曲下载'),
    ('rm13b', 'fiveyy', '23语言页原生', '7新手原生'),
    ('rm13b', 'hxlist', '8红心歌单', '4首页进二级页'),
    ('rm13b', 'jrlpy', '7流派插屏', '4首页进二级页'),
    ('rm13b', 'jrmvplay', '11MV播放页', '切换MV播放'),
    ('rm13b', 'jrzjlist', '10自建&收藏歌单', '4首页进二级页'),
    ('rm13b', 'leopn', '1冷启动', '1冷启动'),
    ('rm13b', 'lqxcad', '15歌曲播放', '5歌曲播放'),
    ('rm13b', 'lxdjxad', '14切歌', '9切歌'),
    ('rm13b', 'reopn', '2热启动', '2热启动'),
    ('rm13b', 'singerzy', '6歌手插屏', '4首页进二级页'),
    ('rm13b', 'songgd', '5歌单插屏', '4首页进二级页'),
    ('rm13b', 'ssjgq', '12点击搜索', '8搜索'),
    ('rm13b', 'ydyad', '3新手插屏', '3新手插屏'),
    ('rm13b', 'zjbflist', '21最近播放原生', '最近播放原生'),
    ('rm13b', 'zjxqy', '4专辑插屏', '4首页进二级页'),
    ('rmi2', 'albumint', '4专辑插屏', '4首页进二级页'),
    ('rmi2', 'albumnav', '20专辑原生', '专辑原生'),
    ('rmi2', 'all', 'ALL', 'ALL'),
    ('rmi2', 'coldopen', '1冷启动', '1冷启动'),
    ('rmi2', 'cuslistint', '10自建&收藏歌单', '4首页进二级页'),
    ('rmi2', 'hotopen', '2热启动', '2热启动'),
    ('rmi2', 'leadingint', '3新手插屏', '3新手插屏'),
    ('rmi2', 'likedint', '8红心歌单', '4首页进二级页'),
    ('rmi2', 'nextsongint', '14切歌', '9切歌'),
    ('rmi2', 'playint', '15歌曲播放', '5歌曲播放'),
    ('rmi2', 'playlistnav', '19歌单原生', '歌单原生'),
    ('rmi2', 'recentint', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rmi2', 'returnint', '13返回', '6返回'),
    ('rmi2', 'searchint', '12点击搜索', '8搜索'),
    ('rmi2', 'searchnav', '22搜索原生', '搜索原生'),
    ('rmi2', 'singerint', '6歌手插屏', '4首页进二级页'),
    ('rmi2', 'singernav', '18歌手原生', '歌手原生'),
    ('rmi2', 'tabnav', '17首页原生', '首页原生'),
    ('rmi3', 'all', 'ALL', 'ALL'),
    ('rmi3', 'coldopen', '1冷启动', '1冷启动'),
    ('rmi3', 'fanhuiint', '13返回', '6返回'),
    ('rmi3', 'gedannav', '19歌单原生', '歌单原生'),
    ('rmi3', 'geshouint', '6歌手插屏', '4首页进二级页'),
    ('rmi3', 'geshounav', '18歌手原生', '歌手原生'),
    ('rmi3', 'hongxinint', '8红心歌单', '4首页进二级页'),
    ('rmi3', 'hotopen', '2热启动', '2热启动'),
    ('rmi3', 'leadint', '3新手插屏', '3新手插屏'),
    ('rmi3', 'lixianint', '24离线歌单插屏', '离线歌单插屏'),
    ('rmi3', 'playernav', '17首页原生', '首页原生'),
    ('rmi3', 'playingint', '15歌曲播放', '5歌曲播放'),
    ('rmi3', 'qiegeint', '14切歌', '9切歌'),
    ('rmi3', 'sousnav', '22搜索原生', '搜索原生'),
    ('rmi3', 'sousuoint', '12点击搜索', '8搜索'),
    ('rmi3', 'yyybignv', '23语言页原生', '7新手原生'),
    ('rmi3', 'zhuanjiint', '4专辑插屏', '4首页进二级页'),
    ('rmi3', 'zhuanjinav', '20专辑原生', '专辑原生'),
    ('rmi3', 'zijianint', '10自建&收藏歌单', '4首页进二级页'),
    ('rmi3', 'zuijinint', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rmi5', 'all', 'ALL', 'ALL'),
    ('rmi5', 'gdxqynav', '19歌单原生', '歌单原生'),
    ('rmi5', 'lqbfint', '15歌曲播放', '5歌曲播放'),
    ('rmi5', 'lqdkp', '1冷启动', '1冷启动'),
    ('rmi5', 'lxdjint', '14切歌', '9切歌'),
    ('rmi5', 'offlineint', '24离线歌单插屏', '离线歌单插屏'),
    ('rmi5', 'recentint', '9最近播放&本地资源歌单', '4首页进二级页'),
    ('rmi5', 'rqdkp', '2热启动', '2热启动'),
    ('rmi5', 'schxint', '8红心歌单', '4首页进二级页'),
    ('rmi5', 'sgymint', '13返回', '6返回'),
    ('rmi5', 'singerint', '6歌手插屏', '4首页进二级页'),
    ('rmi5', 'singernav', '18歌手原生', '歌手原生'),
    ('rmi5', 'ssjgqint', '12点击搜索', '8搜索'),
    ('rmi5', 'sslnav', '22搜索原生', '搜索原生'),
    ('rmi5', 'tabsmnav', '17首页原生', '首页原生'),
    ('rmi5', 'ydyint', '3新手插屏', '3新手插屏'),
    ('rmi5', 'zjgdint', '10自建&收藏歌单', '4首页进二级页'),
    ('rmi5', 'zjxqint', '4专辑插屏', '4首页进二级页'),
    ('rmi5', 'zjxqynav', '20专辑原生', '专辑原生'),
    ('rmi6', 'all', 'ALL', 'ALL'),
    ('rmi6', 'coldopen', '1冷启动', '1冷启动'),
    ('rmi6', 'ffhhint', '13返回', '6返回'),
    ('rmi6', 'ggssint', '6歌手插屏', '4首页进二级页'),
    ('rmi6', 'ggssnav', '18歌手原生', '歌手原生'),
    ('rmi6', 'ggxqnav', '19歌单原生', '歌单原生'),
    ('rmi6', 'hhxxint', '8红心歌单', '4首页进二级页'),
    ('rmi6', 'hotopen', '2热启动', '2热启动'),
    ('rmi6', 'llxxint', '14切歌', '9切歌'),
    ('rmi6', 'llxxnint', '24离线歌单插屏', '离线歌单插屏'),
    ('rmi6', 'ssjgint', '12点击搜索', '8搜索'),
    ('rmi6', 'sslnav', '22搜索原生', '搜索原生'),
    ('rmi6', 'tabbnav', '17首页原生', '首页原生'),
    ('rmi6', 'yuynav', '23语言页原生', '7新手原生'),
    ('rmi6', 'yyddint', '3新手插屏', '3新手插屏'),
    ('rmi6', 'zjxqnav', '20专辑原生', '专辑原生'),
    ('rmi6', 'zzbfint', '15歌曲播放', '5歌曲播放'),
    ('rmi6', 'zzjjint', '10自建&收藏歌单', '4首页进二级页'),
    ('vc001', 'all', 'ALL', 'ALL'),
    ('vc001', 'back_int', '5返回插屏（点击虚拟的返回键也算）', '6返回'),
    ('vc001', 'cold_open', '1冷启动', '1冷启动'),
    ('vc001', 'home_banner', '13首页底部banner', '首页banner'),
    ('vc001', 'home_voice_finish_int', '4首页点击任意入口', '4首页进二级页'),
    ('vc001', 'home_voice_finish_int_input_finish', '20首页音频导入完成后', '4首页进二级页'),
    ('vc001', 'home_voice_finish_int_microphone_finish', '19首页麦克风录音完成后', '4首页进二级页'),
    ('vc001', 'home_voice_finish_int_piano_edit', '22我的作品点击钢琴的钢琴编辑', '4首页进二级页'),
    ('vc001', 'home_voice_finish_int_record_edit', '21我的作品点击录音的作品编辑', '4首页进二级页'),
    ('vc001', 'hot_open', '2热启动', '2热启动'),
    ('vc001', 'language_native', '14语言页原生广告', '7新手原生'),
    ('vc001', 'lls_save_int', '10文本转音频保存后插屏', '5功能使用完成'),
    ('vc001', 'new_guide_native', '15新手引导原生广告', '7新手原生'),
    ('vc001', 'noti_ringtone_success_int', '12通知铃声设置成功后插屏', '5功能使用完成'),
    ('vc001', 'piano_edit_save_int', '9钢琴音保存后插屏', '5功能使用完成'),
    ('vc001', 'record_edit_native', '16录音编辑底部原生', '8二级页原生'),
    ('vc001', 'record_edit_save_int', '8录音编辑保存后插屏', '5功能使用完成'),
    ('vc001', 'record_merge_native', '17录音合成页底部原生', '8二级页原生'),
    ('vc001', 'ring_tone_success_int', '11手机铃声设置成功后插屏', '5功能使用完成'),
    ('vc001', 'set_name_int', '3新手插屏', '3新手插屏'),
    ('vc001', 'setting_int', '7首页点设置按钮插屏', '4首页进二级页'),
    ('vc001', 'setting_native', '18设置页底部原生', '4首页进二级页'),
    ('vc001', 'tab_switch_int', '6首页切换TAB（进入首页load插页池）', '4首页进二级页'),
    ('vc001b', 'all', 'ALL', 'ALL'),
    ('vc001b', 'back_int', '5返回插屏（点击虚拟的返回键也算）', '6返回'),
    ('vc001b', 'cold_open', '1冷启动', '1冷启动'),
    ('vc001b', 'home_banner', '13首页底部banner', '首页banner'),
    ('vc001b', 'home_voice_finish_int', '4首页点击任意入口', '4首页进二级页'),
    ('vc001b', 'home_voice_finish_int_input_finish', '20首页音频导入完成后', '4首页进二级页'),
    ('vc001b', 'home_voice_finish_int_microphone_finish', '19首页麦克风录音完成后', '4首页进二级页'),
    ('vc001b', 'home_voice_finish_int_piano_edit', '22我的作品点击钢琴的钢琴编辑', '4首页进二级页'),
    ('vc001b', 'home_voice_finish_int_record_edit', '21我的作品点击录音的作品编辑', '4首页进二级页'),
    ('vc001b', 'hot_open', '2热启动', '2热启动'),
    ('vc001b', 'language_native', '14语言页原生广告', '7新手原生'),
    ('vc001b', 'lls_save_int', '10文本转音频保存后插屏', '5功能使用完成'),
    ('vc001b', 'new_guide_native', '15新手引导原生广告', '7新手原生'),
    ('vc001b', 'noti_ringtone_success_int', '12通知铃声设置成功后插屏', '5功能使用完成'),
    ('vc001b', 'piano_edit_save_int', '9钢琴音保存后插屏', '5功能使用完成'),
    ('vc001b', 'record_edit_native', '16录音编辑底部原生', '8二级页原生'),
    ('vc001b', 'record_edit_save_int', '8录音编辑保存后插屏', '5功能使用完成'),
    ('vc001b', 'record_merge_native', '17录音合成页底部原生', '8二级页原生'),
    ('vc001b', 'ring_tone_success_int', '11手机铃声设置成功后插屏', '5功能使用完成'),
    ('vc001b', 'set_name_int', '3新手插屏', '3新手插屏'),
    ('vc001b', 'setting_int', '7首页点设置按钮插屏', '4首页进二级页'),
    ('vc001b', 'setting_native', '18设置页底部原生', '4首页进二级页'),
    ('vc001b', 'tab_switch_int', '6首页切换TAB（进入首页load插页池）', '4首页进二级页'),
    ('vd001b', 'all', 'ALL', 'ALL'),
    ('vd001b', 'download_createlabel', '13创建下载任务弹窗底部中原生', '8二级页原生'),
    ('vd001b', 'download_finishlabel', '14下载任务完成弹窗底部中原生', '8二级页原生'),
    ('vd001b', 'int_beginner_exit', '3新手插屏', '3新手插屏'),
    ('vd001b', 'int_bookmark_click', '4浏览器书签点击插页', '4首页进二级页'),
    ('vd001b', 'int_download_click', '5下载视频插页', '5功能使用完成'),
    ('vd001b', 'int_media_addvideo', '8本地媒体库添加视频插页', '5功能使用完成'),
    ('vd001b', 'int_media_back', '9本地媒体库返回插页', '6返回'),
    ('vd001b', 'int_player_back', '7播放器返回插页', '6返回'),
    ('vd001b', 'int_tab_click', '6底部tab切换插页', '4首页进二级页'),
    ('vd001b', 'load_coldstart', '1冷启动', '1冷启动'),
    ('vd001b', 'load_hotstart', '2热启动', '2热启动'),
    ('vd001b', 'tab_browser', '10浏览器/首页中间大原生', '首页原生'),
    ('vd001b', 'tab_download', '11下载模块底部小原生', '8二级页原生'),
    ('vd001b', 'tab_media', '12媒体库模块底部小原生', '8二级页原生'),
    ('vd001b', 'vip_unlock', '15会员解锁激励视频', '会员解锁激励视频'),
    ('vd002b', 'all', 'ALL', 'ALL'),
    ('vd002b', 'download_createlabel', '13创建下载任务弹窗底部中原生', '8二级页原生'),
    ('vd002b', 'download_finishlabel', '14下载任务完成弹窗底部中原生', '8二级页原生'),
    ('vd002b', 'int_beginner_exit', '3新手插屏', '3新手插屏'),
    ('vd002b', 'int_bookmark_click', '4浏览器书签点击插页', '4首页进二级页'),
    ('vd002b', 'int_download_click', '5下载视频插页', '5功能使用完成'),
    ('vd002b', 'int_media_addvideo', '8本地媒体库添加视频插页', '5功能使用完成'),
    ('vd002b', 'int_media_back', '9本地媒体库返回插页', '6返回'),
    ('vd002b', 'int_player_back', '7播放器返回插页', '6返回'),
    ('vd002b', 'int_tab_click', '6底部tab切换插页', '4首页进二级页'),
    ('vd002b', 'load_coldstart', '1冷启动', '1冷启动'),
    ('vd002b', 'load_hotstart', '2热启动', '2热启动'),
    ('vd002b', 'tab_browser', '10浏览器/首页中间大原生', '首页原生'),
    ('vd002b', 'tab_download', '11下载模块底部小原生', '8二级页原生'),
    ('vd002b', 'tab_media', '12媒体库模块底部小原生', '8二级页原生'),
    ('vd002b', 'vip_unlock', '15会员解锁激励视频', '会员解锁激励视频'),
    ('vd003b', 'all', 'ALL', 'ALL'),
    ('vd003b', 'int_beginner_exit', '3新手插屏', '3新手插屏'),
    ('vd003b', 'int_bookmark_click', '4浏览器书签点击插页', '4首页进二级页'),
    ('vd003b', 'int_download_click', '5下载视频插页', '5功能使用完成'),
    ('vd003b', 'int_media_add_video', '8本地媒体库添加视频插页', '5功能使用完成'),
    ('vd003b', 'int_media_back', '9本地媒体库返回插页', '6返回'),
    ('vd003b', 'int_player_back', '7播放器返回插页', '6返回'),
    ('vd003b', 'int_tab_click', '6底部tab切换插页', '4首页进二级页'),
    ('vd003b', 'nav_create_download', '13创建下载任务弹窗底部中原生', '8二级页原生'),
    ('vd003b', 'nav_download_finish', '14下载任务完成弹窗底部中原生', '8二级页原生'),
    ('vd003b', 'nav_download_tab', '11下载模块底部小原生', '8二级页原生'),
    ('vd003b', 'nav_homepage', '10浏览器/首页中间大原生', '首页原生'),
    ('vd003b', 'nav_media_tab', '12媒体库模块底部小原生', '8二级页原生'),
    ('vd003b', 'rew_member_unlock', '15会员解锁激励视频', '会员解锁激励视频'),
    ('vd003b', 'splash_cold_open', '1冷启动', '1冷启动'),
    ('vd003b', 'splash_hot_open', '2热启动', '2热启动'),
    ('vd003c', 'all', 'ALL', 'ALL'),
    ('vd003c', 'int_beginner_exit', '3新手插屏', '3新手插屏'),
    ('vd003c', 'int_bookmark_click', '4浏览器书签点击插页', '4首页进二级页'),
    ('vd003c', 'int_download_click', '5下载视频插页', '5功能使用完成'),
    ('vd003c', 'int_media_add_video', '8本地媒体库添加视频插页', '5功能使用完成'),
    ('vd003c', 'int_media_back', '9本地媒体库返回插页', '6返回'),
    ('vd003c', 'int_player_back', '7播放器返回插页', '6返回'),
    ('vd003c', 'int_tab_click', '6底部tab切换插页', '4首页进二级页'),
    ('vd003c', 'nav_create_download', '13创建下载任务弹窗底部中原生', '8二级页原生'),
    ('vd003c', 'nav_download_finish', '14下载任务完成弹窗底部中原生', '8二级页原生'),
    ('vd003c', 'nav_download_tab', '11下载模块底部小原生', '8二级页原生'),
    ('vd003c', 'nav_homepage', '10浏览器/首页中间大原生', '首页原生'),
    ('vd003c', 'nav_media_tab', '12媒体库模块底部小原生', '8二级页原生'),
    ('vd003c', 'rew_member_unlock', '15会员解锁激励视频', '会员解锁激励视频'),
    ('vd003c', 'splash_cold_open', '1冷启动', '1冷启动'),
    ('vd003c', 'splash_hot_open', '2热启动', '2热启动')
  ) AS t (app_code, raw_scene_name, scene_l1_name, scene_l2_name)
),

-- 2. 基础日志清洗（极速过滤，暂不进行任何 JOIN 关联）
base_log AS (
SELECT
  dt,
  app_code,
  app_version,
  country_code,
  CASE WHEN LOWER(network_name) = 'instagram installs' THEN 'facebook' ELSE network_name END AS network_name,
  scene_name,
  ad_id,
  revenue_usd,
  activity_kind,
  event_name
FROM bi_ods.ods_user_adjust_log_rt
WHERE dt >= CURRENT_DATE - INTERVAL '10 days'
  AND dt = installed_at::date
  AND (LOWER(app_code) LIKE '%rm%' OR LOWER(app_code) LIKE '%r3%' OR LOWER(app_code) LIKE '%fr%' 
       OR LOWER(app_code) LIKE '%vd%' OR LOWER(app_code) LIKE '%vc%' OR LOWER(app_code) LIKE '%pt%' 
       OR LOWER(app_code) LIKE '%rl%')
),

-- 3. 广告收益数据独立映射（延迟关联，只对曝光收益日志进行 JOIN，提升效率）
scene_mapped AS (
SELECT
  l.dt,
  l.app_code,
  l.app_version,
  l.country_code,
  l.network_name,
  COALESCE(m.scene_l1_name, l.scene_name) AS standard_scene_name,
  l.ad_id,
  l.revenue_usd
FROM base_log l
LEFT JOIN dim_scene_mapping m
  ON LOWER(l.app_code) = m.app_code
 AND LOWER(l.scene_name) = m.raw_scene_name
WHERE l.activity_kind = 'ad_revenue'
),

scene_data AS (
SELECT
  dt,
  app_code,
  app_version,
  country_code,
  network_name,
  standard_scene_name AS standard_scene,
  COUNT(DISTINCT ad_id) AS ad_user_count, -- Hologres 环境下若产生 NOTICE 告警可替换为 UNIQ(ad_id)
  COUNT(*) AS ad_count,
  COALESCE(SUM(revenue_usd), 0) AS ad_profit
FROM scene_mapped
GROUP BY
  dt,
  app_code,
  app_version,
  country_code,
  network_name,
  standard_scene_name
HAVING COUNT(DISTINCT ad_id) >= 10
),

-- 4. 新用户数统计（独立计算，避免与场景维度交叉产生笛卡尔积）
new_user_data AS (
SELECT
  dt,
  app_code,
  app_version,
  country_code,
  network_name,
  COUNT(DISTINCT ad_id) AS user_count -- Hologres 环境下若产生告警可替换为 UNIQ(ad_id)
FROM base_log
GROUP BY dt, app_code, app_version, country_code, network_name
HAVING COUNT(DISTINCT ad_id) >= 30
),

-- 5. 点击数据独立映射与聚合
click_mapped AS (
SELECT
  l.dt,
  l.app_code,
  l.app_version,
  l.country_code,
  l.network_name,
  COALESCE(m.scene_l1_name, l.scene_name) AS standard_scene_name
FROM base_log l
LEFT JOIN dim_scene_mapping m
  ON LOWER(l.app_code) = m.app_code
 AND LOWER(l.scene_name) = m.raw_scene_name
WHERE l.event_name = 'ad_click'
),

ad_click_data AS (
SELECT
  dt,
  app_code,
  app_version,
  country_code,
  network_name,
  standard_scene_name AS standard_scene,
  COUNT(*) AS ad_click_count
FROM click_mapped
GROUP BY
  dt,
  app_code,
  app_version,
  country_code,
  network_name,
  standard_scene_name
)

-- 6. 主查询多维并列关联
SELECT
  a.dt AS "日期",
  a.country_code AS "国家",
  a.app_code AS "应用",
  a.app_version AS "版本",
  a.network_name AS "渠道",
  b.user_count AS "注册用户",
  a.standard_scene AS "标准广告场景",
  a.ad_user_count AS "曝光人数",
  a.ad_count AS "曝光次数",
  a.ad_profit AS "广告收益",
  COALESCE(c.ad_click_count, 0) AS "点击次数"
FROM scene_data a
INNER JOIN new_user_data b
  ON a.dt = b.dt
  AND a.app_code = b.app_code
  AND a.app_version = b.app_version
  AND a.country_code = b.country_code
  AND a.network_name = b.network_name
LEFT JOIN ad_click_data c
  ON a.dt = c.dt
  AND a.app_code = c.app_code
  AND a.app_version = c.app_version
  AND a.country_code = c.country_code
  AND a.network_name = c.network_name
  AND a.standard_scene = c.standard_scene
ORDER BY a.dt DESC, a.country_code, a.app_code, a.standard_scene;